### ISSUE TITLE
Tests do not properly sandbox the testing environment

### ISSUE THREAD

**Issue by Freso** [sampsyo/beets#1187]
See http://sprunge.us/bBbi from #1185.

**Comment by jrobeson** [comment]
i definitely noticed that the .config directory is not sandboxed when run locally as mentioned in https://github.com/sampsyo/beets/pull/1185

**Comment by sampsyo** [comment]
Can you narrow down which test is causing that?

**Comment by jrobeson** [comment]
here's at least one of them:

```
======================================================================
FAIL: test_cli_config_paths_resolve_relative_to_user_dir (test.test_ui.ConfigTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/johnny/src/beets/test/test_ui.py", line 771, in test_cli_config_paths_resolve_relative_to_user_dir
    os.path.join(self.user_config_dir, 'beets.db'))
AssertionError: u'/home/johnny/.config/beets/beets.db' != u'/tmp/tmphLcwod/.config/beets/beets.db'
- /home/johnny/.config/beets/beets.db
+ /tmp/tmphLcwod/.config/beets/beets.db
```

**Comment by jrobeson** [comment]
So how does you actually run the tests? i've just been simply doing  tox -e SOMEENV   ? Is that correct? I can't say i'm all that familiar with python testing at all.

**Comment by jrobeson** [comment]
on that note. is there any way to log all test failures to a file instead of just redirecting all the output from tox to a file?

**Comment by sampsyo** [comment]
Weird. I have never seen this failure before. Any chance you can narrow down what it is about your system that's causing it?

On running the tests: see the Testing wiki page (and the docs for Nose, our usual test runner).

**Comment by jrobeson** [comment]
i always forget to check wikis . i went to the docs, and the readme.. but not the wiki!

**Comment by jrobeson** [comment]
this command doesn't work:
```bash
 cd test ; python testall.py
Traceback (most recent call last):
  File "testall.py", line 24, in <module>
    from test._common import unittest
ImportError: No module named _common
```
neither does this one:
```bash
[johnny@falling ~/src/beets (master)]$ python setup.py test
running test
Searching for responses
Reading https://pypi.python.org/simple/responses/
Best match: responses 0.3.0
Downloading https://pypi.python.org/packages/source/r/responses/responses-0.3.0.tar.gz#md5=0181b98153639dccdb5c5daa2ce317da
Processing responses-0.3.0.tar.gz
Writing /tmp/easy_install-uhTcg5/responses-0.3.0/setup.cfg
Running responses-0.3.0/setup.py -q bdist_egg --dist-dir /tmp/easy_install-uhTcg5/responses-0.3.0/egg-dist-tmp-Tud7bC
creating /home/johnny/src/beets/.eggs/responses-0.3.0-py2.7.egg
Extracting responses-0.3.0-py2.7.egg to /home/johnny/src/beets/.eggs

Installed /home/johnny/src/beets/.eggs/responses-0.3.0-py2.7.egg
Searching for rarfile
Reading https://pypi.python.org/simple/rarfile/
Best match: rarfile 2.7
Downloading https://pypi.python.org/packages/source/r/rarfile/rarfile-2.7.tar.gz#md5=d143205f22078830451e0066c123580d
Processing rarfile-2.7.tar.gz
Writing /tmp/easy_install-ONAFiz/rarfile-2.7/setup.cfg
Running rarfile-2.7/setup.py -q bdist_egg --dist-dir /tmp/easy_install-ONAFiz/rarfile-2.7/egg-dist-tmp-xzOTQp
zip_safe flag not set; analyzing archive contents...
Moving rarfile-2.7-py2.7.egg to /home/johnny/src/beets/.eggs

Installed /home/johnny/src/beets/.eggs/rarfile-2.7-py2.7.egg
Searching for mock
Reading https://pypi.python.org/simple/mock/
Best match: mock 1.0.1
Downloading https://pypi.python.org/packages/source/m/mock/mock-1.0.1.zip#md5=869f08d003c289a97c1a6610faf5e913
Processing mock-1.0.1.zip
Writing /tmp/easy_install-k8Jc6m/mock-1.0.1/setup.cfg
Running mock-1.0.1/setup.py -q bdist_egg --dist-dir /tmp/easy_install-k8Jc6m/mock-1.0.1/egg-dist-tmp-hD3Vam
warning: no files found matching '*.png' under directory 'docs'
warning: no files found matching '*.css' under directory 'docs'
warning: no files found matching '*.html' under directory 'docs'
warning: no files found matching '*.js' under directory 'docs'
zip_safe flag not set; analyzing archive contents...
Moving mock-1.0.1-py2.7.egg to /home/johnny/src/beets/.eggs

Installed /home/johnny/src/beets/.eggs/mock-1.0.1-py2.7.egg
running egg_info
writing requirements to beets.egg-info/requires.txt
writing beets.egg-info/PKG-INFO
writing top-level names to beets.egg-info/top_level.txt
writing dependency_links to beets.egg-info/dependency_links.txt
writing entry points to beets.egg-info/entry_points.txt
reading manifest file 'beets.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
no previously-included directories found matching 'docs/_build'
warning: no previously-included files matching '.DS_Store' found anywhere in distribution
writing manifest file 'beets.egg-info/SOURCES.txt'
running build_ext
Traceback (most recent call last):
  File "setup.py", line 135, in <module>
    'Programming Language :: Python :: 2.7',
  File "/usr/lib64/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/lib64/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib64/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/home/johnny/.local/lib/python2.7/site-packages/setuptools/command/test.py", line 142, in run
    self.with_project_on_sys_path(self.run_tests)
  File "/home/johnny/.local/lib/python2.7/site-packages/setuptools/command/test.py", line 122, in with_project_on_sys_path
    func()
  File "/home/johnny/.local/lib/python2.7/site-packages/setuptools/command/test.py", line 163, in run_tests
    testRunner=self._resolve_as_ep(self.test_runner),
  File "/usr/lib64/python2.7/unittest/main.py", line 94, in __init__
    self.parseArgs(argv)
  File "/usr/lib64/python2.7/unittest/main.py", line 149, in parseArgs
    self.createTests()
  File "/usr/lib64/python2.7/unittest/main.py", line 158, in createTests
    self.module)
  File "/usr/lib64/python2.7/unittest/loader.py", line 130, in loadTestsFromNames
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "/usr/lib64/python2.7/unittest/loader.py", line 115, in loadTestsFromName
    test = obj()
  File "/home/johnny/src/beets/test/testall.py", line 46, in suite
    s.addTest(__import__(modname).suite())
  File "/home/johnny/src/beets/test/test_art.py", line 23, in <module>
    import responses
  File "/home/johnny/src/beets/.eggs/responses-0.3.0-py2.7.egg/responses.py", line 24, in <module>
    if six.PY2:
AttributeError: 'module' object has no attribute 'PY2'
```

**Comment by jrobeson** [comment]
oh.. i should mention that nosetests does though.

**Comment by jrobeson** [comment]
nosetests does fail on missing modules. should i have to install them myself?
```bash
[johnny@falling ~/src/beets (master)]$ nosetests
E................................................................................................E..........................................................................................EE..E...................................................................EE.......EE................................................SS...............S...............................................................................EEE.......................................................................................................................................................................................................................................................................................................................................................................................S...................................E...............................EEE......SSSE..........................E..................................................E......EEE.................
======================================================================
ERROR: Failure: ImportError (No module named responses)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/nose/loader.py", line 414, in loadTestsFromName
    addr.filename, addr.module)
  File "/usr/lib/python2.7/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/lib/python2.7/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/home/johnny/src/beets/test/test_art.py", line 23, in <module>
    import responses
ImportError: No module named responses
-------------------- >> begin captured logging << --------------------
musicbrainzngs: DEBUG: set user-agent to beets/1.3.14 python-musicbrainzngs/0.5 ( http://beets.radbox.org/ )
--------------------- >> end captured logging << ---------------------

======================================================================
ERROR: Failure: ImportError (No module named mock)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/nose/loader.py", line 414, in loadTestsFromName
    addr.filename, addr.module)
  File "/usr/lib/python2.7/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/lib/python2.7/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/home/johnny/src/beets/test/test_config_command.py", line 6, in <module>
    from mock import patch
ImportError: No module named mock

======================================================================
ERROR: Failure: ImportError (No module named mock)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/nose/loader.py", line 414, in loadTestsFromName
    addr.filename, addr.module)
  File "/usr/lib/python2.7/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/lib/python2.7/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/home/johnny/src/beets/test/test_echonest.py", line 20, in <module>
    from mock import Mock, patch
ImportError: No module named mock

======================================================================
ERROR: Failure: ImportError (No module named mock)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/nose/loader.py", line 414, in loadTestsFromName
    addr.filename, addr.module)
  File "/usr/lib/python2.7/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/lib/python2.7/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/home/johnny/src/beets/test/test_embedart.py", line 20, in <module>
    from mock import patch
ImportError: No module named mock

======================================================================
ERROR: Failure: ImportError (No module named mock)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/nose/loader.py", line 414, in loadTestsFromName
    addr.filename, addr.module)
  File "/usr/lib/python2.7/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/lib/python2.7/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/home/johnny/src/beets/test/test_filefilter.py", line 27, in <module>
    from test.test_importer import ImportHelper
  File "/home/johnny/src/beets/test/test_importer.py", line 29, in <module>
    from mock import patch
ImportError: No module named mock

======================================================================
ERROR: Failure: ImportError (No module named mock)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/nose/loader.py", line 414, in loadTestsFromName
    addr.filename, addr.module)
  File "/usr/lib/python2.7/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/lib/python2.7/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/home/johnny/src/beets/test/test_importadded.py", line 23, in <module>
    from test.test_importer import ImportHelper, AutotagStub
  File "/home/johnny/src/beets/test/test_importer.py", line 29, in <module>
    from mock import patch
ImportError: No module named mock

======================================================================
ERROR: Failure: ImportError (No module named mock)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/nose/loader.py", line 414, in loadTestsFromName
    addr.filename, addr.module)
  File "/usr/lib/python2.7/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/lib/python2.7/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/home/johnny/src/beets/test/test_importer.py", line 29, in <module>
    from mock import patch
ImportError: No module named mock

======================================================================
ERROR: Failure: ImportError (No module named mock)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/nose/loader.py", line 414, in loadTestsFromName
    addr.filename, addr.module)
  File "/usr/lib/python2.7/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/lib/python2.7/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/home/johnny/src/beets/test/test_keyfinder.py", line 18, in <module>
    from mock import patch
ImportError: No module named mock

======================================================================
ERROR: Failure: ImportError (No module named mock)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/nose/loader.py", line 414, in loadTestsFromName
    addr.filename, addr.module)
  File "/usr/lib/python2.7/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/lib/python2.7/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/home/johnny/src/beets/test/test_lastgenre.py", line 20, in <module>
    from mock import Mock
ImportError: No module named mock

======================================================================
ERROR: Failure: ImportError (No module named mock)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/nose/loader.py", line 414, in loadTestsFromName
    addr.filename, addr.module)
  File "/usr/lib/python2.7/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/lib/python2.7/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/home/johnny/src/beets/test/test_lyrics.py", line 25, in <module>
    from mock import MagicMock
ImportError: No module named mock

======================================================================
ERROR: Failure: ImportError (No module named mock)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/nose/loader.py", line 414, in loadTestsFromName
    addr.filename, addr.module)
  File "/usr/lib/python2.7/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/lib/python2.7/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/home/johnny/src/beets/test/test_mb.py", line 24, in <module>
    import mock
ImportError: No module named mock

======================================================================
ERROR: Failure: ImportError (No module named mock)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/nose/loader.py", line 414, in loadTestsFromName
    addr.filename, addr.module)
  File "/usr/lib/python2.7/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/lib/python2.7/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/home/johnny/src/beets/test/test_mbsync.py", line 18, in <module>
    from mock import patch
ImportError: No module named mock

======================================================================
ERROR: Failure: ImportError (No module named mock)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/nose/loader.py", line 414, in loadTestsFromName
    addr.filename, addr.module)
  File "/usr/lib/python2.7/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/lib/python2.7/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/home/johnny/src/beets/test/test_mpdstats.py", line 19, in <module>
    from mock import Mock
ImportError: No module named mock

======================================================================
ERROR: Failure: ImportError (No module named responses)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/nose/loader.py", line 414, in loadTestsFromName
    addr.filename, addr.module)
  File "/usr/lib/python2.7/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/lib/python2.7/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/home/johnny/src/beets/test/test_plexupdate.py", line 7, in <module>
    import responses
ImportError: No module named responses

======================================================================
ERROR: Failure: ImportError (No module named mock)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/nose/loader.py", line 414, in loadTestsFromName
    addr.filename, addr.module)
  File "/usr/lib/python2.7/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/lib/python2.7/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/home/johnny/src/beets/test/test_plugins.py", line 19, in <module>
    from mock import patch, Mock
ImportError: No module named mock

======================================================================
ERROR: Failure: ImportError (No module named mock)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/nose/loader.py", line 414, in loadTestsFromName
    addr.filename, addr.module)
  File "/usr/lib/python2.7/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/lib/python2.7/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/home/johnny/src/beets/test/test_query.py", line 21, in <module>
    from mock import patch
ImportError: No module named mock

======================================================================
ERROR: Failure: ImportError (No module named mock)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/nose/loader.py", line 414, in loadTestsFromName
    addr.filename, addr.module)
  File "/usr/lib/python2.7/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/lib/python2.7/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/home/johnny/src/beets/test/test_smartplaylist.py", line 22, in <module>
    from mock import Mock, MagicMock
ImportError: No module named mock

======================================================================
ERROR: Failure: ImportError (No module named responses)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/nose/loader.py", line 414, in loadTestsFromName
    addr.filename, addr.module)
  File "/usr/lib/python2.7/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/lib/python2.7/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/home/johnny/src/beets/test/test_spotify.py", line 7, in <module>
    import responses
ImportError: No module named responses

======================================================================
ERROR: Failure: ImportError (No module named mock)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/nose/loader.py", line 414, in loadTestsFromName
    addr.filename, addr.module)
  File "/usr/lib/python2.7/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/lib/python2.7/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/home/johnny/src/beets/test/test_thumbnails.py", line 19, in <module>
    from mock import Mock, patch, call
ImportError: No module named mock

======================================================================
ERROR: Failure: ImportError (No module named mock)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/nose/loader.py", line 414, in loadTestsFromName
    addr.filename, addr.module)
  File "/usr/lib/python2.7/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/lib/python2.7/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/home/johnny/src/beets/test/test_ui.py", line 27, in <module>
    from mock import patch
ImportError: No module named mock

======================================================================
ERROR: Failure: ImportError (No module named mock)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/nose/loader.py", line 414, in loadTestsFromName
    addr.filename, addr.module)
  File "/usr/lib/python2.7/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/lib/python2.7/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/home/johnny/src/beets/test/test_ui_importer.py", line 25, in <module>
    from test import test_importer
  File "/home/johnny/src/beets/test/test_importer.py", line 29, in <module>
    from mock import patch
ImportError: No module named mock

======================================================================
ERROR: Failure: ImportError (No module named mock)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/nose/loader.py", line 414, in loadTestsFromName
    addr.filename, addr.module)
  File "/usr/lib/python2.7/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/lib/python2.7/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/home/johnny/src/beets/test/test_util.py", line 24, in <module>
    from mock import patch, Mock
ImportError: No module named mock

----------------------------------------------------------------------
Ran 979 tests in 82.292s

FAILED (SKIP=7, errors=22)
```

**Comment by sampsyo** [comment]
Yes. You can look in `tox.ini` for a list, or just run tox (as you discovered before) to use them automatically.

**Comment by jrobeson** [comment]
yep.. still getting this one:
```
======================================================================
FAIL: test_cli_config_paths_resolve_relative_to_user_dir (test.test_ui.ConfigTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/johnny/src/beets/test/test_ui.py", line 771, in test_cli_config_paths_resolve_relative_to_user_dir
    os.path.join(self.user_config_dir, 'beets.db'))
AssertionError: u'/home/johnny/.config/beets/beets.db' != u'/tmp/tmp8SGumf/.config/beets/beets.db'
- /home/johnny/.config/beets/beets.db
+ /tmp/tmp8SGumf/.config/beets/beets.db
```

**Comment by jrobeson** [comment]
I'm also getting a ton of test failures like this
```
======================================================================
ERROR: test_threaded_import_move_deletes_import (test.test_ui_importer.NonAutotaggedImportTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/johnny/src/beets/test/test_importer.py", line 309, in test_threaded_import_move_deletes_import
    self.importer.run()
  File "/home/johnny/src/beets/beets/importer.py", line 316, in run
    pl.run_parallel(QUEUE_SIZE)
  File "/home/johnny/src/beets/beets/util/pipeline.py", line 301, in run
    out = self.coro.send(msg)
  File "/home/johnny/src/beets/beets/util/pipeline.py", line 183, in coro
    func(*(args + (task,)))
  File "/home/johnny/src/beets/beets/importer.py", line 1343, in plugin_stage
    func(session, task)
  File "/home/johnny/src/beets/beets/plugins.py", line 123, in wrapper
    return func(*args, **kwargs)
  File "/home/johnny/src/beets/beetsplug/fetchart.py", line 348, in fetch_art
    path = self.art_for_album(task.album, task.paths, local)
  File "/home/johnny/src/beets/beetsplug/fetchart.py", line 426, in art_for_album
    cover_names = self.config['cover_names'].as_str_seq()
  File "/home/johnny/src/beets/beets/util/confit.py", line 388, in as_str_seq
    return self.get(StrSeq())
  File "/home/johnny/src/beets/beets/util/confit.py", line 374, in get
    return as_template(template).value(self, template)
  File "/home/johnny/src/beets/beets/util/confit.py", line 974, in value
    raise NotFoundError("{0} not found".format(view.name))
NotFoundError: fetchart.cover_names not found
```

**Comment by jrobeson** [comment]
```
======================================================================
ERROR: test_cli_config_file_loads_plugin_commands (test.test_ui.ConfigTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/johnny/src/beets/test/test_ui.py", line 803, in test_cli_config_file_loads_plugin_commands
    ui._raw_main(['--config', cli_config_path, 'plugin'])
  File "/home/johnny/src/beets/beets/ui/__init__.py", line 1090, in _raw_main
    subcommands, plugins, lib = _setup(options, lib)
  File "/home/johnny/src/beets/beets/ui/__init__.py", line 978, in _setup
    lib = _open_library(config)
  File "/home/johnny/src/beets/beets/ui/__init__.py", line 1051, in _open_library
    util.displayable_path(dbpath)
UserError: database file /tmp/tmprbJH9a/.local/share/beets/library.db could not be opened
```
I wonder if it's related to this one?

**Comment by jrobeson** [comment]
```
======================================================================
ERROR: test_album_art (test.test_zero.ZeroPluginTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/johnny/src/beets/test/test_zero.py", line 101, in test_album_art
    item.write()
  File "/home/johnny/src/beets/beets/library.py", line 572, in write
    plugins.send('write', item=self, path=path, tags=item_tags)
  File "/home/johnny/src/beets/beets/plugins.py", line 455, in send
    result = handler(**arguments)
  File "/home/johnny/src/beets/beets/plugins.py", line 123, in wrapper
    return func(*args, **kwargs)
  File "./beetsplug/scrub.py", line 144, in write_item
    if not scrubbing and self.config['auto']:
  File "/home/johnny/src/beets/beets/util/confit.py", line 267, in __nonzero__
    return self.__bool__()
  File "/home/johnny/src/beets/beets/util/confit.py", line 272, in __bool__
    return bool(self.get())
  File "/home/johnny/src/beets/beets/util/confit.py", line 374, in get
    return as_template(template).value(self, template)
  File "/home/johnny/src/beets/beets/util/confit.py", line 974, in value
    raise NotFoundError("{0} not found".format(view.name))
NotFoundError: scrub.auto not found
```

**Comment by sampsyo** [comment]
I don't see any obvious root cause here. Maybe there's an ordering effect with other tests?

**Comment by sampsyo** [comment]
This issue is timing out. Please reopen it if this is still going on for you, @jrobeson.

**Comment by jrobeson** [comment]
I haven't had to run the tests since then. I'll open another bug if i need to again.
