### ISSUE TITLE
chroma plugin causes an error: AttributeError: 'module' object has no attribute 'adapters'

### ISSUE THREAD

**Issue by jasonblewis** [sampsyo/beets#1197]
I've followed the instructions for installing the chroma plugin and when I run beets, I get the following error:

```
$ beet import Souad\ Massi/Deb\ \(Heart\ Broken\)/
** error loading plugin chroma
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/beets/plugins.py", line 201, in load_plugins
    namespace = __import__(modname, None, None)
  File "/usr/local/lib/python2.7/dist-packages/beetsplug/chroma.py", line 24, in <module>
    import acoustid
  File "/usr/local/lib/python2.7/dist-packages/acoustid.py", line 126, in <module>
    class CompressedHTTPAdapter(requests.adapters.HTTPAdapter):
AttributeError: 'module' object has no attribute 'adapters'
```

**Comment by jasonblewis** [comment]
beets version 1.3.9
plugins: inline, web, discogs, fromfilename, convert

**Comment by sampsyo** [comment]
Hi! Can you check that you have the latest version of `requests` by typing `pip install -U requests`?

**Comment by jasonblewis** [comment]
That seems to have fixed it! thanks (I seemed to have a very old version of requests)
