### ISSUE TITLE
Crash when no arguments passed

### ISSUE THREAD

**Issue by tstackhouse** [sampsyo/beets#1205]
After upgrading, running `beet` with no arguments yeilds a Python error:

~~~
Traceback (most recent call last):
  File "/usr/local/bin/beet", line 9, in <module>
    load_entry_point('beets==1.3.10', 'console_scripts', 'beet')()
  File "/usr/local/lib/python2.7/dist-packages/beets/ui/__init__.py", line 945, in main
    _raw_main(args)
  File "/usr/local/lib/python2.7/dist-packages/beets/ui/__init__.py", line 927, in _raw_main
    if subargs[0] == 'config' and ('-e' in subargs or '--edit' in subargs):
IndexError: list index out of range
~~~

`beet version` output:

~~~
beets version 1.3.10
plugins: copyartifacts, fetchart, duplicates, chroma, lastgenre, fromfilename, ftintitle
~~~

`python --version`:

~~~
Python 2.7.6
~~~

**Comment by brunal** [comment]
This was caused by the recent addition of a special case for `beets config --edit`.
