### ISSUE TITLE
UnicodeEncodeError exception when importing

### ISSUE THREAD

**Issue by Jaxan** [sampsyo/beets#1214]
I was imprting my music, and it crashed on '†' by Justice:
```
joshua@Joshuas-MacBook-Pro:~/Music$ beet import --pretend Justice/†
Traceback (most recent call last):
  File "/usr/local/bin/beet", line 9, in <module>
    load_entry_point('beets==1.3.10', 'console_scripts', 'beet')()
  File "/usr/local/lib/python2.7/site-packages/beets/ui/__init__.py", line 945, in main
    _raw_main(args)
  File "/usr/local/lib/python2.7/site-packages/beets/ui/__init__.py", line 935, in _raw_main
    subcommand.func(lib, suboptions, subargs)
  File "/usr/local/lib/python2.7/site-packages/beets/ui/commands.py", line 873, in import_func
    import_files(lib, paths, query)
  File "/usr/local/lib/python2.7/site-packages/beets/ui/commands.py", line 845, in import_files
    session.run()
  File "/usr/local/lib/python2.7/site-packages/beets/importer.py", line 305, in run
    pl.run_parallel(QUEUE_SIZE)
  File "/usr/local/lib/python2.7/site-packages/beets/util/pipeline.py", line 345, in run
    self.coro.send(msg)
  File "/usr/local/lib/python2.7/site-packages/beets/util/pipeline.py", line 158, in coro
    task = func(*(args + (task,)))
  File "/usr/local/lib/python2.7/site-packages/beets/importer.py", line 1306, in log_files
    log.info('Album {0}'.format(displayable_path(task.paths[0])))
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2020' in position 28: ordinal not in range(128)
```
beets version 1.3.10
mac osx 10.9.5

**Comment by sampsyo** [comment]
Thanks! Should be fixed now.
