### ISSUE TITLE
latest git pull from 14.01.2015 causes problem...

### ISSUE THREAD

**Issue by jmwatte** [sampsyo/beets#1223]
I just did a git pull at 14-01-2015 at 14:42:00 and when I run beet it gives me this ..

[~/buildtests/beets]$ beet
Traceback (most recent call last):
  File "/usr/local/bin/beet", line 20, in <module>
    beets.ui.main()
  File "/home/winters/buildtests/beets/beets/ui/__init__.py", line 946, in main
    _raw_main(args)
  File "/home/winters/buildtests/beets/beets/ui/__init__.py", line 932, in _raw_main
    subcommands, plugins, lib = _setup(options, lib)
  File "/home/winters/buildtests/beets/beets/ui/__init__.py", line 832, in _setup
    plugins = _load_plugins(config)
  File "/home/winters/buildtests/beets/beets/ui/__init__.py", line 818, in _load_plugi
    plugins.send("pluginload")
  File "/home/winters/buildtests/beets/beets/plugins.py", line 453, in send
    for handler in event_handlers()[event]:
  File "/home/winters/buildtests/beets/beets/plugins.py", line 438, in event_handlers
    for plugin in find_plugins():
  File "/home/winters/buildtests/beets/beets/plugins.py", line 286, in find_plugins
    _instances[cls] = cls()
  File "/home/winters/buildtests/beets/beetsplug/replaygain.py", line 631, in __init__
    self.config, self._log
TypeError: __init__() takes exactly 2 arguments (3 given)

I tried it with beet ls or beet help ... everything gives the same message/
Any ideas?
grtz
jm

**Comment by brunal** [comment]
That was an error on the GStreamer backend (it was not updated to expect a logger). I just fixed it, can you pull and try again?

**Comment by jmwatte** [comment]
Ok mixed. Thnx jm
Sent using CloudMagic
On wo, jan. 14, 2015 at 4:20 PM, Bruno <notifications@github.com> wrote:That was an error on the GStreamer backend (it was not updated to expect a logger). I just fixed it, can you pull and try again?
