### ISSUE TITLE
Beets throws error on MusicBrainz match.

### ISSUE THREAD

**Issue by driesken** [sampsyo/beets#1224]
I've found out that a match with MusicBrainz throws the following error when the original mp3 already had tags. When I remove the original tags first, it succeeds.

/usr/share/beets/beet import -C -s ./01 Mis manos en tu cintura.mp3

/home/ddegendt/.mp3organizer_temporary_files/01 Mis manos en tu cintura.mp3
Tagging track: Adamo - Mis manos en tu cintura
(Similarity: 100.0%)
ERROR mp3(121): mp3 tag parsing ./01 Mis manos en tu cintura.mp3 failed!
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/kaa/metadata/audio/mp3.py", line 113, in __init__
    id3 = eyeD3_tag.Mp3AudioFile(file.name)
  File "/usr/lib/python2.7/dist-packages/kaa/metadata/audio/eyeD3/tag.py", line 1592, in __init__
    hasTag = self.tag.link(f, tagVersion);
  File "/usr/lib/python2.7/dist-packages/kaa/metadata/audio/eyeD3/tag.py", line 469, in link
    padding = self.__loadV2Tag(f);
  File "/usr/lib/python2.7/dist-packages/kaa/metadata/audio/eyeD3/tag.py", line 1325, in __loadV2Tag
    raise TagException(str(ex));
TagException: Invalid frame id for DateFrame: TYER

ERROR mp3(121): mp3 tag parsing ./01 Mis manos en tu cintura.mp3 failed!
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/kaa/metadata/audio/mp3.py", line 113, in __init__
    id3 = eyeD3_tag.Mp3AudioFile(file.name)
  File "/usr/lib/python2.7/dist-packages/kaa/metadata/audio/eyeD3/tag.py", line 1592, in __init__
    hasTag = self.tag.link(f, tagVersion);
  File "/usr/lib/python2.7/dist-packages/kaa/metadata/audio/eyeD3/tag.py", line 469, in link
    padding = self.__loadV2Tag(f);
  File "/usr/lib/python2.7/dist-packages/kaa/metadata/audio/eyeD3/tag.py", line 1325, in __loadV2Tag
    raise TagException(str(ex));
TagException: Invalid frame id for DateFrame: TYER

ERROR mp3(121): mp3 tag parsing ./01 Mis manos en tu cintura.mp3 failed!
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/kaa/metadata/audio/mp3.py", line 113, in __init__
    id3 = eyeD3_tag.Mp3AudioFile(file.name)
  File "/usr/lib/python2.7/dist-packages/kaa/metadata/audio/eyeD3/tag.py", line 1592, in __init__
    hasTag = self.tag.link(f, tagVersion);
  File "/usr/lib/python2.7/dist-packages/kaa/metadata/audio/eyeD3/tag.py", line 469, in link
    padding = self.__loadV2Tag(f);
  File "/usr/lib/python2.7/dist-packages/kaa/metadata/audio/eyeD3/tag.py", line 1325, in __loadV2Tag
    raise TagException(str(ex));
TagException: Invalid frame id for DateFrame: TYER

Is there an option to make beets only show the tags it has found on MusicBrainz? That way I could tag it with another tool.

**Comment by sampsyo** [comment]
I am flummoxed by this. Those tracebacks show a crash inside eyeD3, a library that beets does not use at all.

Do you have third-party plugins installed?

**Comment by driesken** [comment]
I currently have the following plugins enabled:
plugins: mbsync chroma fetchart embedart

**Comment by sampsyo** [comment]
Again, flummoxed. I don't see any way that beets could be using eyeD3. Can you perhaps try uninstalling that Python library to see what happens?

**Comment by sampsyo** [comment]
Also, what is this file that shows up in the traceback?

    /usr/lib/python2.7/dist-packages/kaa/metadata/audio/mp3.py

**Comment by driesken** [comment]
File 'mp3.py' was used by python-kaa-metadata. Removed it and the error seems to be gone.

Thanks!

**Comment by sampsyo** [comment]
So weird—I have no idea why beets would have called into this library. Mysterious!
