### ISSUE TITLE
latest build on 2015/01/27 fetchrart problem

### ISSUE THREAD

**Issue by jmwatte** [sampsyo/beets#1274]
latest build downlloaded at 2015/01/27 07:08

it gives this problem with  beet version or beet import .

[~_downloads]$ beet import -t --flat .
** error loading plugin fetchart
Traceback (most recent call last):
  File "/home/winters/buildtests/beets/beets/plugins.py", line 261, in load_plugins
    namespace = __import__(modname, None, None)
  File "/home/winters/buildtests/beets/beetsplug/fetchart.py", line 28, in <module>
    from beets import importer
  File "/home/winters/buildtests/beets/beets/importer.py", line 47, in <module>
    'ALBUMS'])
  File "/usr/local/lib/python2.7/dist-packages/enum/__init__.py", line 325, in __call__
    return cls._create_(value, names, module=module, type=type)
  File "/usr/local/lib/python2.7/dist-packages/enum/__init__.py", line 433, in _create_
    enum_class = metacls.__new__(metacls, class_name, bases, classdict)
  File "/usr/local/lib/python2.7/dist-packages/enum/__init__.py", line 190, in __new__
    enum_class = super(EnumMeta, metacls).__new__(metacls, cls, bases, classdict)
TypeError: type() argument 1 must be string, not unicode

Traceback (most recent call last):
  File "/usr/local/bin/beet", line 20, in <module>
    beets.ui.main()
  File "/home/winters/buildtests/beets/beets/ui/__init__.py", line 927, in main
    _raw_main(args)
  File "/home/winters/buildtests/beets/beets/ui/__init__.py", line 913, in _raw_main
    subcommands, plugins, lib = _setup(options, lib)
  File "/home/winters/buildtests/beets/beets/ui/__init__.py", line 816, in _setup
    from beets.ui.commands import default_commands
  File "/home/winters/buildtests/beets/beets/ui/commands.py", line 34, in <module>
    from beets import importer
  File "/home/winters/buildtests/beets/beets/importer.py", line 47, in <module>
    'ALBUMS'])
  File "/usr/local/lib/python2.7/dist-packages/enum/__init__.py", line 325, in __call__
    return cls._create_(value, names, module=module, type=type)
  File "/usr/local/lib/python2.7/dist-packages/enum/__init__.py", line 433, in _create_
    enum_class = metacls.__new__(metacls, class_name, bases, classdict)
  File "/usr/local/lib/python2.7/dist-packages/enum/__init__.py", line 190, in __new__
    enum_class = super(EnumMeta, metacls).__new__(metacls, cls, bases, classdict)
TypeError: type() argument 1 must be string, not unicode

grtz
jm

**Comment by sampsyo** [comment]
You have installed the wrong enum package. You want enum34,

**Comment by jmwatte** [comment]
this is a part what I get when I run pip list

Cython (0.20.1post0)
decorator (3.4.0)
discogs-client (2.0.2)
dnspython (1.11.1)
docutils (0.11)
enum34 (0.9.23)
eyeD3 (0.7.5)
eyeD3-pip (0.6.19)
feedparser (5.1.3)
httplib2 (0.9)
ipython (1.2.1)
Jinja2 (2.7.2)

So it looks like it's there.
All the previous version of beet were running perfectly. 
Has something been changed regarding this enum34?
grtz jm

**Comment by sampsyo** [comment]
Can you try upgrading the library with `pip install -U enum34`?

**Comment by jmwatte** [comment]
Yup, 
I was reading up on pip and enum34 and saw they had a new version. The upgrading did it.
oeffff.... back to enjoying beet.
Thx alot
jm
