### ISSUE TITLE
beet ls -f'$title' gives unicode error??

### ISSUE THREAD

**Issue by jmwatte** [sampsyo/beets#1278]
if I do a beet ls like this... I get ...

$ beet ls the best classi ever lascia
George Frideric Handel - The Best Classics...Ever! - Lascia Chíoi Pianga (Rinaldo) (Arr. Craig Leon & Isobel Cooper)

but if I do this ... I get ...

$ beet ls the best classi ever lascia -f '$title'
Traceback (most recent call last):
  File "/usr/local/bin/beet", line 20, in <module>
    beets.ui.main()
  File "/home/winters/buildtests/beets/beets/ui/__init__.py", line 927, in main
    _raw_main(args)
  File "/home/winters/buildtests/beets/beets/ui/__init__.py", line 917, in _raw_main
    subcommand.func(lib, suboptions, subargs)
  File "/home/winters/buildtests/beets/beets/ui/commands.py", line 965, in list_func
    list_items(lib, decargs(args), opts.album, fmt)
  File "/home/winters/buildtests/beets/beets/ui/commands.py", line 960, in list_items
    ui.print_(format(item, fmt))
  File "/home/winters/buildtests/beets/beets/ui/__init__.py", line 110, in print_
    txt = ' '.join(strings)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 9: ordinal not in range(128)

Did I catch something here ? :)

grtz
jm

**Comment by sampsyo** [comment]
Which version or git commit do you have?

**Comment by jmwatte** [comment]
oeps, soryy forgot ...

$ beet version                            
beets version 1.3.11
plugins: convert, dates, embedart, fuzzy, fromfilename, scrub, inline, replaygain, lastgenre, amazon, bpd, fetchart, play, ftintitle, info, random, duplicates, smartplaylist

I'll do a git pull right now to be uptodate

**Comment by jmwatte** [comment]
ahh.... after a git pull ... the problem is gone.
my bad... :(

**Comment by sampsyo** [comment]
Ok, thanks!
