### ISSUE TITLE
Handle shlex parse errors in query strings

### ISSUE THREAD

**Issue by kooimens** [sampsyo/beets#1290]
When trying to import a certain directory with beets i'm getting an error. Don't know what this is. I'm using Ubuntu Server 14.04. 

```
Traceback (most recent call last):
  File "/usr/local/bin/beet", line 9, in <module>
    load_entry_point('beets==1.3.10', 'console_scripts', 'beet')()
  File "/usr/local/lib/python2.7/dist-packages/beets/ui/__init__.py", line 945, in main
    _raw_main(args)
  File "/usr/local/lib/python2.7/dist-packages/beets/ui/__init__.py", line 935, in _raw_main
    subcommand.func(lib, suboptions, subargs)
  File "/usr/local/lib/python2.7/dist-packages/beets/ui/commands.py", line 873, in import_func
    import_files(lib, paths, query)
  File "/usr/local/lib/python2.7/dist-packages/beets/ui/commands.py", line 845, in import_files
    session.run()
  File "/usr/local/lib/python2.7/dist-packages/beets/importer.py", line 305, in run
    pl.run_parallel(QUEUE_SIZE)
  File "/usr/local/lib/python2.7/dist-packages/beets/util/pipeline.py", line 345, in run
    self.coro.send(msg)
  File "/usr/local/lib/python2.7/dist-packages/beets/util/pipeline.py", line 158, in coro
    task = func(*(args + (task,)))
  File "/usr/local/lib/python2.7/dist-packages/beets/importer.py", line 1291, in manipulate_files
    session=session,
  File "/usr/local/lib/python2.7/dist-packages/beets/importer.py", line 635, in manipulate_files
    item.move(copy, link)
  File "/usr/local/lib/python2.7/dist-packages/beets/library.py", line 611, in move
    dest = self.destination(basedir=basedir)
  File "/usr/local/lib/python2.7/dist-packages/beets/library.py", line 653, in destination
    query, _ = parse_query_string(query, type(self))
  File "/usr/local/lib/python2.7/dist-packages/beets/library.py", line 1016, in parse_query_string
    parts = [p.decode('utf8') for p in shlex.split(s)]
  File "/usr/lib/python2.7/shlex.py", line 279, in split
    return list(lex)
  File "/usr/lib/python2.7/shlex.py", line 269, in next
    token = self.get_token()
  File "/usr/lib/python2.7/shlex.py", line 96, in get_token
    raw = self.read_token()
  File "/usr/lib/python2.7/shlex.py", line 172, in read_token
    raise ValueError, "No closing quotation"
ValueError: No closing quotation
```

**Comment by sampsyo** [comment]
Thanks for reporting; we need a better error message in any case. I believe this is an error in your path format config—can you paste that, please?

**Comment by kooimens** [comment]
That's really fast! Thanks for helping me out. Here is it: 
![1](https://cloud.githubusercontent.com/assets/3150962/5986616/4d09427e-a8ff-11e4-8e7d-ef83310bb390.jpg)

and 
`item_fields:
    disc_unpadded: 1 if disc == 0 else str(disc)`

**Comment by kooimens** [comment]
Hmm, I commented out the first line of my path format and everything seems to work fine again.

**Comment by sampsyo** [comment]
Yes, you have an unbalanced " on that line.

**Comment by brunal** [comment]
Improved version:
```
>>> parse_query_string('mb_trackid::^$":', Album)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/bru/code/beets/beets/library.py", line 1075, in parse_query_string
    raise ValueError("Cannot parse {0!r} (error was: {1})".format(s, exc))
ValueError: Cannot parse 'mb_trackid::^$":' (error was: No closing quotation)
```

Being able to do `raise ValueError("Cannot parse {0!r}".format(s)) from exc` would be sooo cool :-)

**Comment by sampsyo** [comment]
Yeah, I'm certainly envious of [chained expressions](https://www.python.org/dev/peps/pep-3134/) in Python 3.

What do you think about using `InvalidQueryError` so that the user gets a prettier, traceback-free error message?

**Comment by brunal** [comment]
I'm not sure about `InvalidQueryError`: it is currently quite low-level, belonging in `beets.db.query`.
Moreover the current formatting does not fit. Maybe there should be a more generic `InvalidQueryError` (residing in which module?, problem **1**) that would be raised here, and then an `InvalidQueryArgumentTypeError` (that's a bit long for a name, problem **2**) extending `InvalidQueryError` in `beets.db.query`.

**Comment by sampsyo** [comment]
Good points all. I think I lean toward your option **2**, with a new subclass for `parse_query_string`-specific parse errors like this. A completely new exception would seem to be fine too.

**Comment by brunal** [comment]
Ok I'm working on it. What do you think of putting `InvalidQueryError` in `beets.util`? Moreover I have to tweak `beets.dbcore.beets` so the error raised by queries is enriched with the query itself.

I'm leaving for holidays, I'll wrap it up when in a week.

**Comment by sampsyo** [comment]
Hmm, I'd say no to locating it in `beets.util` since it doesn't fit with the standalone utilities there; `dbcore` seems like the right place for this.

Bon voyage! Thank you for looking into this!

**Comment by brunal** [comment]
Here it is! As you hinted the 2 exception classes are not directly related: `InvalidQueryError` wants the query, which `InvalidQueryArgumentTypeError` does not know.
