### ISSUE TITLE
import --pretend crashes on files with unicode names

### ISSUE THREAD

**Issue by azrdev** [sampsyo/beets#1336]
I have an album that uses non-ascii characters (e.g. `é`) in its track names, and also in the filenames. `beet import` works fine on these files, however, `beet import --pretend` would give me the following backtrace:
```
Traceback (most recent call last):
  File "/usr/bin/beet", line 9, in <module>
    load_entry_point('beets==1.3.10', 'console_scripts', 'beet')()
  File "/home/azrdev/.local/lib/python2.7/site-packages/beets/ui/__init__.py", line 945, in main
    _raw_main(args)
  File "/home/azrdev/.local/lib/python2.7/site-packages/beets/ui/__init__.py", line 935, in _raw_main
    subcommand.func(lib, suboptions, subargs)
  File "/home/azrdev/.local/lib/python2.7/site-packages/beets/ui/commands.py", line 873, in import_func
    import_files(lib, paths, query)
  File "/home/azrdev/.local/lib/python2.7/site-packages/beets/ui/commands.py", line 845, in import_files
    session.run()
  File "/home/azrdev/.local/lib/python2.7/site-packages/beets/importer.py", line 305, in run
    pl.run_parallel(QUEUE_SIZE)
  File "/home/azrdev/.local/lib/python2.7/site-packages/beets/util/pipeline.py", line 345, in run
    self.coro.send(msg)
  File "/home/azrdev/.local/lib/python2.7/site-packages/beets/util/pipeline.py", line 158, in coro
    task = func(*(args + (task,)))
  File "/home/azrdev/.local/lib/python2.7/site-packages/beets/importer.py", line 1308, in log_files
    log.info('  {0}'.format(displayable_path(item['path'])))
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 36: ordinal not in range(128)
```
Renaming some file to be only ascii-named fixed this, so it's probably not the tags fault.

**Comment by sampsyo** [comment]
Which version of beets are you running? If you're not already, can you try this on the latest git revision to see if it's fixed? (I think we fixed something similar recently.)

**Comment by azrdev** [comment]
as it says at the top of the trace, 1.3.10
as for current HEAD, let me check :-)

**Comment by azrdev** [comment]
just tested c91e8cb and confirmed it is fixed there

**Comment by sampsyo** [comment]
Thanks!
