### ISSUE TITLE
Unicode TypeError 

### ISSUE THREAD

**Issue by hkhanna** [sampsyo/beets#1356]
Starting with commit 927a53d59b9d1b08065e4f9866c2a6193cd1fa79, my beets stopped working. I get the following output when I try to import a singleton track:

```
$ beet -v import -s 01\ American\ Girl.mp3
user configuration: /home/harry/.config/beets/config.yaml
data directory: /home/harry/.config/beets
** error loading plugin zero
Traceback (most recent call last):
  File "/home/harry/src/beets/beets/plugins.py", line 261, in load_plugins
    namespace = __import__(modname, None, None)
  File "/home/harry/src/beets/beetsplug/zero.py", line 23, in <module>
    from beets.importer import action
  File "/home/harry/src/beets/beets/importer.py", line 47, in <module>
    'ALBUMS'])
  File "/usr/local/lib/python2.7/dist-packages/enum/__init__.py", line 321, in __call__
    return cls._create_(value, names, module=module, type=type)
  File "/usr/local/lib/python2.7/dist-packages/enum/__init__.py", line 429, in _create_
    enum_class = metacls.__new__(metacls, class_name, bases, classdict)
  File "/usr/local/lib/python2.7/dist-packages/enum/__init__.py", line 183, in __new__
    enum_class = super(EnumMeta, metacls).__new__(metacls, cls, bases, classdict)
TypeError: type() argument 1 must be string, not unicode

Sending event: pluginload
Traceback (most recent call last):
  File "/home/harry/bin/beet", line 20, in <module>
    beets.ui.main()
  File "/home/harry/src/beets/beets/ui/__init__.py", line 953, in main
    _raw_main(args)
  File "/home/harry/src/beets/beets/ui/__init__.py", line 939, in _raw_main
    subcommands, plugins, lib = _setup(options, lib)
  File "/home/harry/src/beets/beets/ui/__init__.py", line 834, in _setup
    from beets.ui.commands import default_commands
  File "/home/harry/src/beets/beets/ui/commands.py", line 34, in <module>
    from beets import importer
  File "/home/harry/src/beets/beets/importer.py", line 47, in <module>
    'ALBUMS'])
  File "/usr/local/lib/python2.7/dist-packages/enum/__init__.py", line 321, in __call__
    return cls._create_(value, names, module=module, type=type)
  File "/usr/local/lib/python2.7/dist-packages/enum/__init__.py", line 429, in _create_
    enum_class = metacls.__new__(metacls, class_name, bases, classdict)
  File "/usr/local/lib/python2.7/dist-packages/enum/__init__.py", line 183, in __new__
    enum_class = super(EnumMeta, metacls).__new__(metacls, cls, bases, classdict)
TypeError: type() argument 1 must be string, not unicode
```

The commit merges a pull request to create user configurable colors. If I roll back to the commit immediately preceding this one (0947b8f286764e5a13c4ce0ce504dd8e7e38ea8a), it works just fine. I'm using Python 2.7.

**Comment by sampsyo** [comment]
Can you try upgrading enum34?

    $ pip install -U enum34

**Comment by hkhanna** [comment]
That did the trick. Any idea what the problem was?

**Comment by sampsyo** [comment]
Great!

We started requiring a slightly newer version of the library. The upgrade should happen automatically when people `pip install -U beets` but I think this dependency update gets missed if you just pull from git.

**Comment by hkhanna** [comment]
Great, thanks for the update.
