### ISSUE TITLE
TypeError: 'Subview' object is not iterable when running beet lastimport

### ISSUE THREAD

**Issue by yoasif** [sampsyo/beets#1365]
I'm running the latest source version of beets and running lastimport for my last.fm user yoasif. The import fails on the first page of results with "TypeError: 'Subview' object is not iterable".

I'm running beets on an up to date copy of Ubuntu Utopic.

    $ beet -v lastimport
    Warning: top-level configuration of `color` is deprecated. Configure color use under `ui`. See documentation for more info.
    user configuration: /home/asif/.config/beets/config.yaml
    data directory: /home/asif/.config/beets
    plugin paths: 
    Sending event: pluginload
    inline: adding item field multidisc
    library database: /home/asif/.musiclibrary.blb
    library directory: /quadra/music/Downloaded Albums
    Sending event: library_opened
    lastimport: Fetching last.fm library for @yoasif
    lastimport: Querying page #1...
    Traceback (most recent call last):
      File "/usr/local/bin/beet", line 9, in <module>
        load_entry_point('beets==1.3.11', 'console_scripts', 'beet')()
      File "/usr/local/lib/python2.7/dist-packages/beets/ui/__init__.py", line 1081, in main
        _raw_main(args)
      File "/usr/local/lib/python2.7/dist-packages/beets/ui/__init__.py", line 1071, in _raw_main
        subcommand.func(lib, suboptions, subargs)
      File "/usr/local/lib/python2.7/dist-packages/beetsplug/lastimport.py", line 47, in func
        import_lastfm(lib, self._log)
      File "/usr/local/lib/python2.7/dist-packages/beetsplug/lastimport.py", line 74, in import_lastfm
        page = fetch_tracks(user, page_current + 1, per_page)
      File "/usr/local/lib/python2.7/dist-packages/beetsplug/lastimport.py", line 113, in fetch_tracks
        'format': 'json',
      File "/usr/lib/python2.7/dist-packages/requests/api.py", line 55, in get
        return request('get', url, **kwargs)
      File "/usr/lib/python2.7/dist-packages/requests/api.py", line 44, in request
        return session.request(method=method, url=url, **kwargs)
      File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 422, in request
        prep = self.prepare_request(req)
      File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 360, in prepare_request
        hooks=merge_hooks(request.hooks, self.hooks),
      File "/usr/lib/python2.7/dist-packages/requests/models.py", line 294, in prepare
        self.prepare_url(url, params)
      File "/usr/lib/python2.7/dist-packages/requests/models.py", line 380, in prepare_url
        enc_params = self._encode_params(params)
      File "/usr/lib/python2.7/dist-packages/requests/models.py", line 88, in _encode_params
        for v in vs:
      File "/usr/local/lib/python2.7/dist-packages/beets/util/confit.py", line 218, in __iter__
        u"iterable".format(self.__class__.__name__))
    TypeError: 'Subview' object is not iterable

    $ beet version
    Warning: top-level configuration of `color` is deprecated. Configure color use under `ui`. See documentation for more info.
    beets version 1.3.11
    plugins: chroma, mbcollection, missing, permissions, scrub, fetchart, lastgenre, inline, embedart, echonest, mbsync, web, lastimport

**Comment by sampsyo** [comment]
Thanks! This is one of those "I have no idea how this ever worked" situations. But this should fix it.
