### ISSUE TITLE
Reimporting an existing album causes a traceback error when finding duplicates

### ISSUE THREAD

**Issue by amishb** [sampsyo/beets#1367]
## Repo Steps:
1. Import an album into beets
2. Import the exact same album into beets again. 

## Error:
Album is recognised tagged, and says album already exists but also causes a traceback error:

```
 * Gettin Jiggy Wit It ->
   Gettin' Jiggy Wit It
 * Miami
 * Freakin It ->
   Freakin' It
 * Will 2k (Ft. K-Ci) ->
   Will 2K (title)
 * Wild Wild West (Ft. Dru Hill & Kool Moe Dee) ->
   Wild Wild West (title)
 * Nod Ya Head (The Remix) (Ft. Christina Vidal en Trá-Knox) ->
   Nod Ya Head (The Remix) (title)
 * Just The Two Of Us ->
   Just the Two of Us
This album is already in the library!
Traceback (most recent call last):
  File "/home/admin/.virtualenvs/beetsdev/bin/beet", line 9, in <module>
    load_entry_point('beets==1.3.11', 'console_scripts', 'beet')()
  File "/home/admin/python/beets/beets/ui/__init__.py", line 1081, in main
    _raw_main(args)
  File "/home/admin/python/beets/beets/ui/__init__.py", line 1071, in _raw_main
    subcommand.func(lib, suboptions, subargs)
  File "/home/admin/python/beets/beets/ui/commands.py", line 892, in import_func
    import_files(lib, paths, query)
  File "/home/admin/python/beets/beets/ui/commands.py", line 869, in import_files
    session.run()
  File "/home/admin/python/beets/beets/importer.py", line 316, in run
    pl.run_parallel(QUEUE_SIZE)
  File "/home/admin/python/beets/beets/util/pipeline.py", line 301, in run
    out = self.coro.send(msg)
  File "/home/admin/python/beets/beets/util/pipeline.py", line 160, in coro
    task = func(*(args + (task,)))
  File "/home/admin/python/beets/beets/importer.py", line 1287, in user_query
    resolve_duplicates(session, task)
  File "/home/admin/python/beets/beets/importer.py", line 1299, in resolve_duplicates
    session.resolve_duplicate(task, found_duplicates)
  File "/home/admin/python/beets/beets/ui/commands.py", line 783, in resolve_duplicate
    real_duplicates = filter(len, found_duplicates)
TypeError: object of type 'Album' has no len()
```

I saw that @brunal made a commit bcfdcdc4b768c138c074a4ac599623f7e3f35066 which added new functionality which is where this error is occurring.

Happy to provide any more info. 

Config:

```
  1 directory: /mounts/backup/music
  2 library: /mounts/backup/music/beetslibrary.db
  3
  4 import:
  5     move: no
  6     copy: yes
  7     write: yes
  8     resume: ask
  9     detail: yes
 10
 11 plugins:
 12     ftintitle
 13
 14 paths:
 15     default: $albumartist/$year - $album/$track - $title
 16     singleton: ZZMusic/$artist - $track - $title
 17     comp: Various Artists/$year - $album/$track - $title
 18
 19 ui:
 20     terminal_width: 120
 21     color: yes
 22     colors:
 23         text_success: green
 24         text_warning: yellow
 25         text_error: red
 26         text_highlight: red
 27         text_highlight_minor: lightgray
 28         action_default: turquoise
 29         action: blue
 30
 31 time_format: '%Y-%m-%d %H:%M:%S'
 32
 33 ftintitle:
 34     auto: yes
 35     drop: no
```

**Comment by brunal** [comment]
Well I did break it. I knew I should've written tests. I'm on it.

**Comment by amishb** [comment]
Hi @brunal I built from your commit, and am not seeing this error anymore. Just thought I would retest with your latest commit. Let me know if you want me to retest with any more usecases.

**Comment by brunal** [comment]
Cool. Since I did not find an easy & satisfying way to test this I'm cowardly closing this issue...
