### ISSUE TITLE
"beet" command by itself gives error

### ISSUE THREAD

**Issue by alphapapa** [sampsyo/beets#1373]
```
$ beet
Traceback (most recent call last):
  File "/home/me/.local/bin/beet", line 9, in <module>
    load_entry_point('beets==1.3.10', 'console_scripts', 'beet')()
  File "/home/me/.local/lib/python2.7/site-packages/beets/ui/__init__.py", line 945, in main
    _raw_main(args)
  File "/home/me/.local/lib/python2.7/site-packages/beets/ui/__init__.py", line 927, in _raw_main
    if subargs[0] == 'config' and ('-e' in subargs or '--edit' in subargs):
IndexError: list index out of range

$ beet help
Usage: 
  beet COMMAND [ARGS...]
  beet help COMMAND

Options:
  -l LIBRARY, --library=LIBRARY
                        library database file to use
  -d DIRECTORY, --directory=DIRECTORY
                        destination music directory
  -v, --verbose         print debugging information
  -c CONFIG, --config=CONFIG
                        path to configuration file
  -h, --help            how this help message and exit

Commands:
  config            show or edit the user configuration
  fields            show fields available for queries and format strings
  help (?)          give detailed help on a specific sub-command
  import (imp, im)  import new music
  list (ls)         query the library
  modify (mod)      change metadata fields
  move (mv)         move or copy items
  remove (rm)       remove matching items from the library
  stats             show statistics about the library or a query
  update (upd, up)  update the library
  version           output version information
  write             write tag information to files
```
I think `beet` should give the same output as `beet help`.

Sorry if this issue already exists, but there are a lot of issues in the system, and I couldn't find one about this.

**Comment by brunal** [comment]
This was reported in #1205 and subsequently fixed in the development version. If it bothers you please install a more recent version of beets, otherwise wait for the 3.11 release.

**Comment by alphapapa** [comment]
Thanks.  Sorry for the dupe; there are so many issues that it's hard to find the old ones sometimes.  It doesn't bother me, I was just trying to help the project.  :)
