### ISSUE TITLE
beet command tracebacks in importer in current master

### ISSUE THREAD

**Issue by jrobeson** [sampsyo/beets#1378]
There's a traceback in both the fetchart plugin , and seemingly the importer module itself. I tried without the fetchart plugin and got the 2nd traceback only. They seem to have the same root cause though.

```bash
$ ./beet write -p
** error loading plugin fetchart
Traceback (most recent call last):
  File "/home/johnny/src/beets/beets/plugins.py", line 257, in load_plugins
    namespace = __import__(modname, None, None)
  File "/home/johnny/src/beets/beetsplug/fetchart.py", line 28, in <module>
    from beets import importer
  File "/home/johnny/src/beets/beets/importer.py", line 47, in <module>
    'ALBUMS'])
  File "/usr/lib/python2.7/site-packages/enum/__init__.py", line 321, in __call__
    return cls._create_(value, names, module=module, type=type)
  File "/usr/lib/python2.7/site-packages/enum/__init__.py", line 429, in _create_
    enum_class = metacls.__new__(metacls, class_name, bases, classdict)
  File "/usr/lib/python2.7/site-packages/enum/__init__.py", line 183, in __new__
    enum_class = super(EnumMeta, metacls).__new__(metacls, cls, bases, classdict)
TypeError: type() argument 1 must be string, not unicode

Traceback (most recent call last):
  File "./beet", line 20, in <module>
    beets.ui.main()
  File "/home/johnny/src/beets/beets/ui/__init__.py", line 1081, in main
    _raw_main(args)
  File "/home/johnny/src/beets/beets/ui/__init__.py", line 1067, in _raw_main
    subcommands, plugins, lib = _setup(options, lib)
  File "/home/johnny/src/beets/beets/ui/__init__.py", line 949, in _setup
    from beets.ui.commands import default_commands
  File "/home/johnny/src/beets/beets/ui/commands.py", line 32, in <module>
    from beets import importer
  File "/home/johnny/src/beets/beets/importer.py", line 47, in <module>
    'ALBUMS'])
  File "/usr/lib/python2.7/site-packages/enum/__init__.py", line 321, in __call__
    return cls._create_(value, names, module=module, type=type)
  File "/usr/lib/python2.7/site-packages/enum/__init__.py", line 429, in _create_
    enum_class = metacls.__new__(metacls, class_name, bases, classdict)
  File "/usr/lib/python2.7/site-packages/enum/__init__.py", line 183, in __new__
    enum_class = super(EnumMeta, metacls).__new__(metacls, cls, bases, classdict)
TypeError: type() argument 1 must be string, not unicode
```

**Comment by sampsyo** [comment]
Please upgrade your enum34 package:

    $ pip install -U enum34

**Comment by jrobeson** [comment]
ah, so the distro version in fedora 21 is not new enough. either that of the semi official Fedora COPR version isn't.

**Comment by jrobeson** [comment]
@afreof can you add an updated version of python-enum34 to your copr repo if the Fedora folks don't seem to be bumping theirs anytime soon?

**Comment by jrobeson** [comment]
@sampsyo:

[root@falling ~]# pip install -U enum34
Requirement already up-to-date: enum34 in /usr/lib/python2.7/site-packages

but uninstalling the distro version and then installing it with pip removed the error.

**Comment by afreof** [comment]
Did you install beets from my copr repo https://copr.fedoraproject.org/coprs/afreof/beets/ ? At least beets 1.3.10 from the repo fetches cover jpgs without tracebacks on my Fedora 21.
Before we update basic python packages such as enum34, I would like to understand the problem. But in general I could do it, of course.

**Comment by jrobeson** [comment]
I only have the the problem when running from the version from git (to test what will become 1.3.11) with ./beet 

I don't think you have to make an rpm after all, as the proper version does exist. I thought (before looking) that the version in the repos was older than what pip would give me, but that is not the case.

However, even though both the pip installed version and the rpm version are 1.04, only the pip installed version works. The python-enum34 rpm gives me the traceback above.

**Comment by afreof** [comment]
Conclusion: The problem seems to be very specific to python-enum34 packaged by Fedora and a pre-release of beets 1.3.11. I will not investigate on that until beets 1.3.11 is officially released. May be Fedora already provides a working python-enum34 update before beets 1.3.11 will be available.
