### ISSUE TITLE
Invoking with no arguments causes an exception instead of a help message

### ISSUE THREAD

**Issue by DanielHeath** [sampsyo/beets#1391]
```
  $ beet --version
beets version 1.3.10
no plugins loaded

  $ beet
Traceback (most recent call last):
  File "/usr/local/bin/beet", line 9, in <module>
    load_entry_point('beets==1.3.10', 'console_scripts', 'beet')()
  File "/usr/local/lib/python2.7/site-packages/beets/ui/__init__.py", line 945, in main
    _raw_main(args)
  File "/usr/local/lib/python2.7/site-packages/beets/ui/__init__.py", line 927, in _raw_main
    if subargs[0] == 'config' and ('-e' in subargs or '--edit' in subargs):
IndexError: list index out of range
```

**Comment by sampsyo** [comment]
Please see #1205.
