### ISSUE TITLE
echonest: UnicodeDecodeError: 'ascii' codec can't decode byte

### ISSUE THREAD

**Issue by autochthe** [sampsyo/beets#1407]
There appears to be a bug in the a way the echonest plugin handles Unicode.  It appears to be improperly trying to decode UTF as ASCII.  This appears to be a regression as this album imported successfully using the echonest plugin in v1.3.10.

This is the traceback of a crash during import:

```
Traceback (most recent call last):
  File "/usr/local/bin/beet", line 9, in <module>
    load_entry_point('beets==1.3.11', 'console_scripts', 'beet')()
  File "/usr/local/lib/python2.7/dist-packages/beets/ui/__init__.py", line 1081, in main
    _raw_main(args)
  File "/usr/local/lib/python2.7/dist-packages/beets/ui/__init__.py", line 1071, in _raw_main
    subcommand.func(lib, suboptions, subargs)
  File "/usr/local/lib/python2.7/dist-packages/beets/ui/commands.py", line 892, in import_func
    import_files(lib, paths, query)
  File "/usr/local/lib/python2.7/dist-packages/beets/ui/commands.py", line 869, in import_files
    session.run()
  File "/usr/local/lib/python2.7/dist-packages/beets/importer.py", line 316, in run
    pl.run_parallel(QUEUE_SIZE)
  File "/usr/local/lib/python2.7/dist-packages/beets/util/pipeline.py", line 301, in run
    out = self.coro.send(msg)
  File "/usr/local/lib/python2.7/dist-packages/beets/util/pipeline.py", line 183, in coro
    func(*(args + (task,)))
  File "/usr/local/lib/python2.7/dist-packages/beets/importer.py", line 1343, in plugin_stage
    func(session, task)
  File "/usr/local/lib/python2.7/dist-packages/beets/plugins.py", line 123, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/beetsplug/echonest.py", line 449, in imported
    song = self.fetch_song(item)
  File "/usr/local/lib/python2.7/dist-packages/beetsplug/echonest.py", line 406, in fetch_song
    song = method(item)
  File "/usr/local/lib/python2.7/dist-packages/beetsplug/echonest.py", line 344, in analyze
    prepared = self.prepare_upload(item)
  File "/usr/local/lib/python2.7/dist-packages/beetsplug/echonest.py", line 271, in prepare_upload
    tmp = source = self.convert(source)
  File "/usr/local/lib/python2.7/dist-packages/beetsplug/echonest.py", line 306, in convert
    util.command_output(opts)
  File "/usr/local/lib/python2.7/dist-packages/beets/util/__init__.py", line 653, in command_output
    cmd=b' '.join(cmd),
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 36: ordinal not in range(128)
```

Tested using beets version 1.3.11 on Raspberry Pi 2 B running Raspbian GNU/Linux 7 (wheezy) 3.18.7-v7+

**Comment by brunal** [comment]
The given command has unicode elements while they should all be byte strings, as per `beets.util.command_output()` docstring.

**Comment by brunal** [comment]
Nevermind about those, I found the problem: it's a 1-char change. Temp file path should be a byte string.

By the way I see that the function (`convert()`) in which this happens does something the `Convert` plugin does very well, maybe it should call the plugin. Thoughts, @sampsyo ?

**Comment by sampsyo** [comment]
Aha, good catch.

Yes, deduplicating the functionality between this and the convert plugin seems like a good plan. We'll need to be careful with cross-plugin imports, though (c.f. 0af2cdaa3a78493fa5483a8786b429e78cfe21fd, an approach that might also be appropriate here).
