### ISSUE TITLE
importadded: Exception upon selecting "as tracks"

### ISSUE THREAD

**Issue by ctlaltdefeat** [sampsyo/beets#1416]
Getting this during an import:
```python
Finding tags for album "Bluetech - ".
Candidates:
1. Bluetech - Sines And Singularities (26.6%) (missing tracks, album, source, ...) (Discogs, CD, 2005, Israel, Aleph Zero Records)
2. Bluetech - The Divine Invasion (26.6%) (missing tracks, album, source, ...) (Discogs, CD, 2009, Israel, Aleph Zero Records)
3. Bluetech - Prima Materia (24.7%) (missing tracks, album, tracks, ...) (Discogs, CD, 2003, US, Waveform Records)
4. Bluetech - Elementary Particles + Prima Materia (20.5%) (missing tracks, album, source, ...) (Discogs, 2xCD, 2004, US, Aleph Zero Records)
5. Bluetech - Love Songs To The Source (20.0%) (missing tracks, album, tracks, ...) (Discogs, CD, 2010, Canada, Interchill Records)
6. Various Artists - Left Coast Liquid, Volume 1 (15.3%) (missing tracks, album) (CD, 2005, US, Native State Records)
# selection (default 1), Skip, Use as-is, as Tracks, Group albums,
Enter search, enter Id, aBort? T
Traceback (most recent call last):
  File "/usr/bin/beet", line 9, in <module>
    load_entry_point('beets==1.3.11', 'console_scripts', 'beet')()
  File "/usr/lib/python2.7/site-packages/beets/ui/__init__.py", line 1081, in main
    _raw_main(args)
  File "/usr/lib/python2.7/site-packages/beets/ui/__init__.py", line 1071, in _raw_main
    subcommand.func(lib, suboptions, subargs)
  File "/usr/lib/python2.7/site-packages/beets/ui/commands.py", line 892, in import_func
    import_files(lib, paths, query)
  File "/usr/lib/python2.7/site-packages/beets/ui/commands.py", line 869, in import_files
    session.run()
  File "/usr/lib/python2.7/site-packages/beets/importer.py", line 316, in run
    pl.run_parallel(QUEUE_SIZE)
  File "/usr/lib/python2.7/site-packages/beets/util/pipeline.py", line 304, in run
    for msg in _allmsgs(out):
  File "/usr/lib/python2.7/site-packages/beets/util/pipeline.py", line 455, in pull
    out = coro.send(msg)
  File "/usr/lib/python2.7/site-packages/beets/util/pipeline.py", line 183, in coro
    func(*(args + (task,)))
  File "/usr/lib/python2.7/site-packages/beets/importer.py", line 1234, in lookup_candidates
    plugins.send('import_task_start', session=session, task=task)
  File "/usr/lib/python2.7/site-packages/beets/plugins.py", line 455, in send
    result = handler(**arguments)
  File "/usr/lib/python2.7/site-packages/beets/plugins.py", line 123, in wrapper
    return func(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/beetsplug/importadded.py", line 53, in record_if_inplace
    for item in task.items:
TypeError: 'NoneType' object is not iterable
```

**Comment by sampsyo** [comment]
Thanks. Looks like the `imoortadded` plugin isn't expecting this case. Any clues, @silb?

**Comment by sampsyo** [comment]
@silb: It looks like in-place imports in `importadded` don't expect singleton tasks. Checking it out.

**Comment by silb** [comment]
@sampsyo  sorry for not responding in a timely manner on this request.

**Comment by sampsyo** [comment]
No worries, @silb! :smiley:
