### ISSUE TITLE
Crash on import

### ISSUE THREAD

**Issue by three80** [sampsyo/beets#1440]
I just upgraded to 1.3.12  and when trying to import it crashes and I'm not sure why 1.3.11 worked just fine.

three80@snubnose:~$ beet imp music
Traceback (most recent call last):
  File "/usr/local/bin/beet", line 9, in <module>
    load_entry_point('beets==1.3.12', 'console_scripts', 'beet')()
  File "/usr/local/lib/python2.7/dist-packages/beets/ui/__init__.py", line 1104, in main
    _raw_main(args)
  File "/usr/local/lib/python2.7/dist-packages/beets/ui/__init__.py", line 1094, in _raw_main
    subcommand.func(lib, suboptions, subargs)
  File "/usr/local/lib/python2.7/dist-packages/beets/ui/commands.py", line 893, in import_func
    import_files(lib, paths, query)
  File "/usr/local/lib/python2.7/dist-packages/beets/ui/commands.py", line 870, in import_files
    session.run()
  File "/usr/local/lib/python2.7/dist-packages/beets/importer.py", line 316, in run
    pl.run_parallel(QUEUE_SIZE)
  File "/usr/local/lib/python2.7/dist-packages/beets/util/pipeline.py", line 301, in run
    out = self.coro.send(msg)
  File "/usr/local/lib/python2.7/dist-packages/beets/util/pipeline.py", line 183, in coro
    func(*(args + (task,)))
  File "/usr/local/lib/python2.7/dist-packages/beets/importer.py", line 1236, in lookup_candidates
    task.lookup_candidates()
  File "/usr/local/lib/python2.7/dist-packages/beets/importer.py", line 567, in lookup_candidates
    autotag.tag_album(self.items)
  File "/usr/local/lib/python2.7/dist-packages/beets/autotag/match.py", line 437, in tag_album
    _add_candidate(items, candidates, info)
  File "/usr/local/lib/python2.7/dist-packages/beets/autotag/match.py", line 354, in _add_candidate
    mapping, extra_items, extra_tracks = assign_items(items, info.tracks)
  File "/usr/local/lib/python2.7/dist-packages/beets/autotag/match.py", line 94, in assign_items
    row.append(track_distance(item, track))
  File "/usr/local/lib/python2.7/dist-packages/beets/autotag/match.py", line 131, in track_distance
    dist.add_string('track_title', item.title, track_info.title)
  File "/usr/local/lib/python2.7/dist-packages/beets/autotag/hooks.py", line 493, in add_string
    dist = string_dist(str1, str2)
  File "/usr/local/lib/python2.7/dist-packages/beets/autotag/hooks.py", line 246, in string_dist
    base_dist = _string_dist_basic(str1, str2)
  File "/usr/local/lib/python2.7/dist-packages/beets/autotag/hooks.py", line 212, in _string_dist_basic
    return levenshtein_distance(str1, str2) / float(max(len(str1), len(str2)))
TypeError: expected unicode, got str

I get this on any folder I try and like I said 1.3.11 was working.

Edit: forgot some info

three80@snubnose:~$ beet version
beets version 1.3.12
plugins: alternatives, chroma, convert, duplicates, embedart, fetchart, fromfilename, info, inline, lastgenre, lyrics, mbsync, missing, play, random, replaygain, rewrite, scrub, zero

config: http://pastebin.com/dSFT6EqT

running beets with -vv : http://pastebin.com/yzjiscFN

**Comment by sampsyo** [comment]
Thanks for the report. This just appeared the other day due to a broken dependency update, and I fixed it here: https://github.com/sampsyo/beets/commit/0e3f6cb09dfc10f813feae861fa41d942ca77290

I'm going to push out a hot-fix release now.
