### ISSUE TITLE
TypeError on windows 8.1 when using fetchart plugin

### ISSUE THREAD

**Issue by noc7c9** [sampsyo/beets#1448]
```
Traceback (most recent call last):
  File "C:\Python27\Scripts\beet-script.py", line 9, in <module>
    load_entry_point('beets==1.3.13', 'console_scripts', 'beet')()
  File "C:\Python27\lib\site-packages\beets\ui\__init__.py", line 1104, in main
    _raw_main(args)
  File "C:\Python27\lib\site-packages\beets\ui\__init__.py", line 1094, in _raw_main
    subcommand.func(lib, suboptions, subargs)
  File "C:\Python27\lib\site-packages\beets\ui\commands.py", line 893, in import_func
    import_files(lib, paths, query)
  File "C:\Python27\lib\site-packages\beets\ui\commands.py", line 870, in import_files
    session.run()
  File "C:\Python27\lib\site-packages\beets\importer.py", line 316, in run
    pl.run_parallel(QUEUE_SIZE)
  File "C:\Python27\lib\site-packages\beets\util\pipeline.py", line 301, in run
    out = self.coro.send(msg)
  File "C:\Python27\lib\site-packages\beets\util\pipeline.py", line 183, in coro
    func(*(args + (task,)))
  File "C:\Python27\lib\site-packages\beets\importer.py", line 1343, in plugin_stage
    func(session, task)
  File "C:\Python27\lib\site-packages\beets\plugins.py", line 123, in wrapper
    return func(*args, **kwargs)
  File "C:\Python27\lib\site-packages\beetsplug\fetchart.py", line 348, in fetch_art
    path = self.art_for_album(task.album, task.paths, local)
  File "C:\Python27\lib\site-packages\beetsplug\fetchart.py", line 443, in art_for_album
    if self._is_valid_image_candidate(candidate):
  File "C:\Python27\lib\site-packages\beetsplug\fetchart.py", line 412, in _is_valid_image_candidate
    size = ArtResizer.shared.get_size(candidate)
  File "C:\Python27\lib\site-packages\beets\util\artresizer.py", line 153, in shared
    cls._instance = cls()
  File "C:\Python27\lib\site-packages\beets\util\artresizer.py", line 165, in __init__
    self.method = self._check_method()
  File "C:\Python27\lib\site-packages\beets\util\artresizer.py", line 219, in _check_method
    version = has_PIL()
  File "C:\Python27\lib\site-packages\beets\util\artresizer.py", line 249, in has_PIL
    __import__('PIL', fromlist=['Image'])
TypeError: Item in ``from list'' not a string
```

An odd error, `'Image'` is unicode, but `__import__` requires a string but only when importing PIL.

```python
>>> __import__('PIL', fromlist=[u'Image'])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: Item in ``from list'' not a string
>>> __import__('PIL', fromlist=['Image'])
<module 'PIL' from 'C:\Python27\lib\site-packages\PIL\__init__.pyc'>
>>> __import__('os', fromlist=[u'path'])
<module 'os' from 'C:\Python27\lib\os.pyc'>
>>> __import__('os', fromlist=['path'])
<module 'os' from 'C:\Python27\lib\os.pyc'>
>>> import sys; sys.version
'2.7.8 (default, Jun 30 2014, 16:03:49) [MSC v.1500 32 bit (Intel)]'
>>> import PIL; PIL.VERSION
'1.1.7'
```

**Comment by noc7c9** [comment]
The obvious fix of changing, line 249 to `__import__('PIL', fromlist=[str('Image')])` works.

**Comment by tomjaspers** [comment]
Good catch @noc7c9, and thanks for verifying the fix !

**Comment by sampsyo** [comment]
Awesome; thanks! Would you mind adding a changelog entry when you get a chance, @tomjaspers?
