### ISSUE TITLE
Permission plugin can't seem to handle non ASCII paths

### ISSUE THREAD

**Issue by jrobeson** [sampsyo/beets#1449]
```bash
[ ~/src/beets (master *)]$ ./beet import /home/johnny/downloads/t/foo/KANA-BOON\ -\ Silhouette/
/home/johnny/downloads/t/foo/KANA-BOON - Silhouette (3 items)
Correcting tags from:
    KANA-BOON - シルエット - Single
To:
    KANA-BOON - シルエット
URL:
    http://musicbrainz.org/release/9f648d74-f3a9-4a47-83c4-0c555149d0a0
(Similarity: 100.0%) (CD, 2014, JP, Ki/oon)
[A]pply, More candidates, Skip, Use as-is, as Tracks, Group albums,
Enter search, enter Id, aBort? A
Traceback (most recent call last):
  File "./beet", line 20, in <module>
    beets.ui.main()
  File "/home/johnny/src/beets/beets/ui/__init__.py", line 1104, in main
    _raw_main(args)
  File "/home/johnny/src/beets/beets/ui/__init__.py", line 1094, in _raw_main
    subcommand.func(lib, suboptions, subargs)
  File "/home/johnny/src/beets/beets/ui/commands.py", line 893, in import_func
    import_files(lib, paths, query)
  File "/home/johnny/src/beets/beets/ui/commands.py", line 870, in import_files
    session.run()
  File "/home/johnny/src/beets/beets/importer.py", line 316, in run
    pl.run_parallel(QUEUE_SIZE)
  File "/home/johnny/src/beets/beets/util/pipeline.py", line 347, in run
    self.coro.send(msg)
  File "/home/johnny/src/beets/beets/util/pipeline.py", line 160, in coro
    task = func(*(args + (task,)))
  File "/home/johnny/src/beets/beets/importer.py", line 1370, in manipulate_files
    task.finalize(session)
  File "/home/johnny/src/beets/beets/importer.py", line 517, in finalize
    self._emit_imported(session.lib)
  File "/home/johnny/src/beets/beets/importer.py", line 547, in _emit_imported
    plugins.send('album_imported', lib=lib, album=self.album)
  File "/home/johnny/src/beets/beets/plugins.py", line 455, in send
    result = handler(**arguments)
  File "/home/johnny/src/beets/beets/plugins.py", line 123, in wrapper
    return func(*args, **kwargs)
  File "/home/johnny/src/beets/beetsplug/permissions.py", line 93, in permissions
    path))
  File "/home/johnny/src/beets/beetsplug/permissions.py", line 41, in dirs_in_library
    if ancestor.startswith(library)][1:]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe3 in position 29: ordinal not in range(128)
```

I printed out the ancestry(item) list and ended up with the result below, which seems valid.
```python
b'\xe3\x82\xb7\xe3\x83\xab\xe3\x82\xa8\xe3\x83\x83\xe3\x83\x88'.decode('utf-8')
'シルエット'
```

EDIT: in case it's not clear. I'm testing this on GNU/Linux (specifically Fedora 21)

**Comment by sampsyo** [comment]
Thanks for the fix! Can you please check that the above commit fixes this?

**Comment by jrobeson** [comment]
yep. it's all good now.
