### ISSUE TITLE
lastgenre crashes out

### ISSUE THREAD

**Issue by darthanubis** [sampsyo/beets#1459]
lastgenre: error in pylast library: list index out of range
lastgenre: error in pylast library: list index out of range
lastgenre: error in pylast library: list index out of range
lastgenre: error in pylast library: list index out of range
lastgenre: error in pylast library: list index out of range
lastgenre: error in pylast library: list index out of range
lastgenre: error in pylast library: list index out of range
lastgenre: error in pylast library: list index out of range
lastgenre: error in pylast library: list index out of range
lastgenre: error in pylast library: list index out of range
lastgenre: error in pylast library: list index out of range
lastgenre: error in pylast library: list index out of range
lastgenre: error in pylast library: list index out of range
lastgenre: error in pylast library: list index out of range
lastgenre: error in pylast library: list index out of range
Traceback (most recent call last):
  File "/usr/local/bin/beet", line 9, in <module>
    load_entry_point('beets==1.3.13', 'console_scripts', 'beet')()
  File "/usr/local/lib/python2.7/dist-packages/beets/ui/__init__.py", line 1104, in main
    _raw_main(args)
  File "/usr/local/lib/python2.7/dist-packages/beets/ui/__init__.py", line 1094, in _raw_main
    subcommand.func(lib, suboptions, subargs)
  File "/usr/local/lib/python2.7/dist-packages/beets/ui/commands.py", line 893, in import_func
    import_files(lib, paths, query)
  File "/usr/local/lib/python2.7/dist-packages/beets/ui/commands.py", line 870, in import_files
    session.run()
  File "/usr/local/lib/python2.7/dist-packages/beets/importer.py", line 316, in run
    pl.run_parallel(QUEUE_SIZE)
  File "/usr/local/lib/python2.7/dist-packages/beets/util/pipeline.py", line 347, in run
    self.coro.send(msg)
  File "/usr/local/lib/python2.7/dist-packages/beets/util/pipeline.py", line 160, in coro
    task = func(*(args + (task,)))
  File "/usr/local/lib/python2.7/dist-packages/beets/importer.py", line 1366, in manipulate_files
    session=session,
  File "/usr/local/lib/python2.7/dist-packages/beets/importer.py", line 661, in manipulate_files
    plugins.send('import_task_files', session=session, task=self)
  File "/usr/local/lib/python2.7/dist-packages/beets/plugins.py", line 455, in send
    result = handler(**arguments)
  File "/usr/local/lib/python2.7/dist-packages/beets/plugins.py", line 123, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/beetsplug/fetchart.py", line 362, in assign_art
    album.set_art(path, not src_removed)
  File "/usr/local/lib/python2.7/dist-packages/beets/library.py", line 1069, in set_art
    plugins.send('art_set', album=self)
  File "/usr/local/lib/python2.7/dist-packages/beets/plugins.py", line 455, in send
    result = handler(**arguments)
  File "/usr/local/lib/python2.7/dist-packages/beets/plugins.py", line 123, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/beetsplug/embedart.py", line 133, in process_album
    self.config['ifempty'].get(bool))
  File "/usr/local/lib/python2.7/dist-packages/beets/art.py", line 94, in embed_album
    compare_threshold, ifempty, as_album=True)
  File "/usr/local/lib/python2.7/dist-packages/beets/art.py", line 72, in embed_item
    item.try_write(path=itempath, tags={'images': [image]})
  File "/usr/local/lib/python2.7/dist-packages/beets/library.py", line 600, in try_write
    self.write(path, tags)
  File "/usr/local/lib/python2.7/dist-packages/beets/library.py", line 582, in write
    mediafile.update(item_tags)
  File "/usr/local/lib/python2.7/dist-packages/beets/mediafile.py", line 1490, in update
    setattr(self, field, dict[field])
  File "/usr/local/lib/python2.7/dist-packages/beets/mediafile.py", line 1110, in __set__
    style.set_list(mediafile.mgfile, values)
  File "/usr/local/lib/python2.7/dist-packages/beets/mediafile.py", line 523, in set_list
    self.store(mutagen_file, [self.serialize(value) for value in values])
  File "/usr/local/lib/python2.7/dist-packages/beets/mediafile.py", line 657, in serialize
    raise ValueError('MP4 files only supports PNG and JPEG images')
ValueError: MP4 files only supports PNG and JPEG images

**Comment by sampsyo** [comment]
Thanks. I actually just fixed this (which is in embedart) yesterday. https://github.com/sampsyo/beets/commit/dff4feaec2aaf2b1cc18164c34f6e3d8993c5e84

**Comment by stefancrain** [comment]
I was seeing this bug also, mine was popping up while I was embedding art. 
```
embedart: Embedding album art into Animal Collective - Campfire Songs
Traceback (most recent call last):
  File "/usr/local/bin/beet", line 9, in <module>
    load_entry_point('beets==1.3.13', 'console_scripts', 'beet')()
  File "/usr/local/lib/python2.7/site-packages/beets/ui/__init__.py", line 1104, in main
    _raw_main(args)
  File "/usr/local/lib/python2.7/site-packages/beets/ui/__init__.py", line 1094, in _raw_main
    subcommand.func(lib, suboptions, subargs)
  File "/usr/local/lib/python2.7/site-packages/beetsplug/embedart.py", line 79, in embed_func
    compare_threshold, ifempty)
  File "/usr/local/lib/python2.7/site-packages/beets/art.py", line 94, in embed_album
    compare_threshold, ifempty, as_album=True)
  File "/usr/local/lib/python2.7/site-packages/beets/art.py", line 72, in embed_item
    item.try_write(path=itempath, tags={'images': [image]})
  File "/usr/local/lib/python2.7/site-packages/beets/library.py", line 600, in try_write
    self.write(path, tags)
  File "/usr/local/lib/python2.7/site-packages/beets/library.py", line 582, in write
    mediafile.update(item_tags)
  File "/usr/local/lib/python2.7/site-packages/beets/mediafile.py", line 1490, in update
    setattr(self, field, dict[field])
  File "/usr/local/lib/python2.7/site-packages/beets/mediafile.py", line 1110, in __set__
    style.set_list(mediafile.mgfile, values)
  File "/usr/local/lib/python2.7/site-packages/beets/mediafile.py", line 523, in set_list
    self.store(mutagen_file, [self.serialize(value) for value in values])
  File "/usr/local/lib/python2.7/site-packages/beets/mediafile.py", line 657, in serialize
    raise ValueError('MP4 files only supports PNG and JPEG images')
ValueError: MP4 files only supports PNG and JPEG images
```
beets version
```
$ beet version
beets version 1.3.13
plugins: chroma, convert, discogs, duplicates, echonest, embedart, fetchart, ftintitle, info, inline, lastgenre, mbsync, missing, scrub, the
```
@sampsyo how do I upgrade to the patch above to test?

**Comment by sampsyo** [comment]
Please see the FAQ.
