### ISSUE TITLE
KeyError: u'WEB-flac'

### ISSUE THREAD

**Issue by kelvinhammond** [sampsyo/beets#1481]
Key Error when importing a flac file.

```python
Traceback (most recent call last):
  File "/usr/lib64/python2.7/logging/__init__.py", line 859, in emit
    msg = self.format(record)
  File "/usr/lib64/python2.7/logging/__init__.py", line 732, in format
    return fmt.format(record)
  File "/usr/lib64/python2.7/logging/__init__.py", line 471, in format
    record.message = record.getMessage()
  File "/usr/lib64/python2.7/logging/__init__.py", line 331, in getMessage
    msg = str(self.msg)
  File "/home/kelvin/beets/beets/logging.py", line 85, in __str__
    return self.msg.format(*args, **kwargs)
KeyError: u'WEB-flac'
Logged from file importer.py, line 1324
```

**Comment by sampsyo** [comment]
Can you provide a little bit more context? What's the filename you were importing, for example? Did it happen to have curly braces `{}` in the name?

My suspicion is that it did, in which case this should be fixed in the above commit.
