### ISSUE TITLE
util.syspath should convert to unicode all paths

### ISSUE THREAD

**Issue by glogiotatidis** [sampsyo/beets#1485]
When on `python2.7` I run `beet thumbnails` I get this error

```
Traceback (most recent call last):
  File "/home/seadog/.virtualenvs/beets/bin/beet", line 9, in <module>
    load_entry_point('beets==1.3.13', 'console_scripts', 'beet')()
  File "/home/seadog/.virtualenvs/beets/local/lib/python2.7/site-packages/beets/ui/__init__.py", line 1104, in main
    _raw_main(args)
  File "/home/seadog/.virtualenvs/beets/local/lib/python2.7/site-packages/beets/ui/__init__.py", line 1094, in _raw_main
    subcommand.func(lib, suboptions, subargs)
  File "/home/seadog/.virtualenvs/beets/local/lib/python2.7/site-packages/beetsplug/thumbnails.py", line 77, in process_query
    self.process_album(album)
  File "/home/seadog/.virtualenvs/beets/local/lib/python2.7/site-packages/beetsplug/thumbnails.py", line 123, in process_album
    size = ArtResizer.shared.get_size(album.artpath)
  File "/home/seadog/.virtualenvs/beets/local/lib/python2.7/site-packages/beets/util/artresizer.py", line 205, in get_size
    return func(path_in)
  File "/home/seadog/.virtualenvs/beets/local/lib/python2.7/site-packages/beets/util/artresizer.py", line 123, in im_getsize
    util.syspath(path_in)])
  File "/home/seadog/.virtualenvs/beets/local/lib/python2.7/site-packages/beets/util/__init__.py", line 633, in command_output
    cmd=b' '.join(cmd),
UnicodeDecodeError: 'ascii' codec can't decode byte 0xce in position 21: ordinal not in range(128)
```

`cmd` contains `[unicode, unicode, unicode, str]` where `str` is the path.

**Comment by untitaker** [comment]
It seems beets uses unicode_literals, this is one of the grave consequences of it.

**Comment by sampsyo** [comment]
Perfect fix; thanks, @unitaker.
