### ISSUE TITLE
Keyfinder crashes on non-ascii filenames.

### ISSUE THREAD

**Issue by JordanSekky** [sampsyo/beets#1502]
Hi, I get the following python error when running keyfinder on my database. I can attach my database, but I'm not sure how to do that. The song that causes problems has a strange unicode character in its name: 02 ❦ (Ripe & Ruin).flac. Let me know how I can further help fix this.

```
keyfinder: added computed initial key Bm for D:\Music\Library\alt-J\An Awesome Wave\01 Intro.flac Traceback (most recent call last):
  File "C:\Python27\Scripts\beet-script.py", line 9, in <module>
    load_entry_point('beets==1.3.13', 'console_scripts', 'beet')()
  File "C:\Python27\lib\site-packages\beets\ui\__init__.py", line 1104, in main
    _raw_main(args)
  File "C:\Python27\lib\site-packages\beets\ui\__init__.py", line 1094, in _raw_main
    subcommand.func(lib, suboptions, subargs)
  File "C:\Python27\lib\site-packages\beetsplug\keyfinder.py", line 50, in command
    write=config['import']['write'].get(bool))
  File "C:\Python27\lib\site-packages\beetsplug\keyfinder.py", line 64, in find_key
    output = util.command_output([bin, '-f', item.path])
  File "C:\Python27\lib\site-packages\beets\util\__init__.py", line 624, in command_output
    shell=shell
  File "C:\Python27\lib\subprocess.py", line 709, in __init__
    errread, errwrite)
  File "C:\Python27\lib\subprocess.py", line 912, in _execute_child
    args = list2cmdline(args)
  File "C:\Python27\lib\subprocess.py", line 644, in list2cmdline
    return ''.join(result)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 0: ordinal not in range(128)
```

**Comment by sampsyo** [comment]
Thanks for reporting! Can you check whether the above fix at least suppresses the error? A full solution may be prevented by a Python bug on Windows (referenced in the commit), but this should at least avoid crashing the program.

**Comment by JordanSekky** [comment]
Hi, I can confirm that my windows machine throws the windows workaround error, then continues operation.

**Comment by sampsyo** [comment]
OK! Sorry this isn't a satisfying fix, but it will have to do for now. :confused:
