### ISSUE TITLE
TypeError: invalid arguments when running 'beet' on the command line.

### ISSUE THREAD

**Issue by drivfe** [sampsyo/beets#1509]
Installed with 'pip install beets'

```
(venv2) C:\Users\User\Rand\PY\beet>beet
Traceback (most recent call last):
  File "C:\Python27\Lib\runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "C:\Python27\Lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Users\User\Rand\PY\beet\venv2\Scripts\beet.exe\__main__.py", line 9, i
n <module>
  File "C:\Users\User\Rand\PY\beet\venv2\lib\site-packages\beets\ui\__init__.py",
 line 1104, in main
    _raw_main(args)
  File "C:\Users\User\Rand\PY\beet\venv2\lib\site-packages\beets\ui\__init__.py",
 line 1068, in _raw_main
    help='library database file to use')
  File "C:\Python27\Lib\optparse.py", line 1018, in add_option
    raise TypeError, "invalid arguments"
TypeError: invalid arguments
```

**Comment by sampsyo** [comment]
Very strange! Thanks for reporting.

Can you give the full detail on your setup? Some examples that would be helpful:

* OS version
* Python version
* when you installed
* whether this occurs when you clone from git instead
* has this ever happened before?
* looks like you're using a virtualenv; have you tried it without venv?

Et cetera.

**Comment by drivfe** [comment]
* Windows 7 Professional SP1
* Python 2.7
* pip 7.0.3 from C:\Python27\lib\site-packages (python 2.7)
* It was my first time trying to install beets.

I tried installing (python setup.py install) after cloning with git and with and without virtualenv but I keep getting the same error.

```
C:\Python27\Scripts>beet.exe
Traceback (most recent call last):
  File "C:\Python27\Scripts\beet-script.py", line 9, in <module>
    load_entry_point('beets==1.3.14', 'console_scripts', 'beet')()
  File "C:\Python27\lib\site-packages\beets-1.3.14-py2.7.egg\beets\ui\__init__.py
", line 1140, in main
    _raw_main(args)
  File "C:\Python27\lib\site-packages\beets-1.3.14-py2.7.egg\beets\ui\__init__.py
", line 1104, in _raw_main
    help='library database file to use')
  File "C:\Python27\Lib\optparse.py", line 1018, in add_option
    raise TypeError, "invalid arguments"
TypeError: invalid arguments
```

**Comment by sampsyo** [comment]
Hmmm… stranger and stranger. Nothing is suspicious in your platform, and I don't see any obvious sources for the problem.

Sure, maybe pasting the `optparse.py` would help. And if you can, could you try putting this line:

    print type(args[0]), types.StringTypes

at the top of the `add_option()` function therein, and running this again? That might help indicate what's wrong.

**Comment by sampsyo** [comment]
I found this bug, which apparently corresponds to Python 2.7.0: http://bugs.python.org/issue9161

Do you have 2.7.0? If so, can you get the latest version instead?

**Comment by drivfe** [comment]
This is the print output:
```
<type 'instance'> (<type 'str'>, <type 'unicode'>)
<type 'instance'> (<type 'str'>, <type 'unicode'>)
<type 'unicode'> (<type 'str'>, <type 'unicode'>)
```

Here is the file: https://gist.github.com/drivfe/ea37909b70d07452b2b0

**Comment by sampsyo** [comment]
Great! Thanks for upgrading.
