### ISSUE TITLE
TypeError: setattr expected 3 arguments, got 2

### ISSUE THREAD

**Issue by JesseWeinstein** [sampsyo/beets#1513]
When I try to use the -t option to the duplicates plugin, I get the following traceback:
```
Traceback (most recent call last):
  File "/usr/local/bin/beet", line 9, in <module>
    load_entry_point('beets==1.3.13', 'console_scripts', 'beet')()
  File "/usr/local/lib/python2.7/dist-packages/beets/ui/__init__.py", line 1104, in main
    _raw_main(args)
  File "/usr/local/lib/python2.7/dist-packages/beets/ui/__init__.py", line 1094, in _raw_main
    subcommand.func(lib, suboptions, subargs)
  File "/usr/local/lib/python2.7/dist-packages/beetsplug/duplicates.py", line 148, in _dup
    fmt=fmt.format(obj_count))
  File "/usr/local/lib/python2.7/dist-packages/beetsplug/duplicates.py", line 170, in _process_item
    setattr(k, v)
TypeError: setattr expected 3 arguments, got 2
```

**Comment by sampsyo** [comment]
Thanks! This appears to already have been fixed on master.

**Comment by JesseWeinstein** [comment]
This seems to be the commit in question: commit 684f4deadc85908f6e376606d74914bf980c8e44. I suppose I'll look into running the development version of beets, at least till the next release comes out. :-)

**Comment by pedros** [comment]
@JesseWeinstein: yeah, sorry about that; it lurked undiscovered for quite some time, actually.
