### ISSUE TITLE
Replaygain gstreamer backend "AttributeError: 'NoneType' object has no attribute 'set_property'"

### ISSUE THREAD

**Issue by hrehfeld** [sampsyo/beets#1518]
I hope this is not a duplicate of the other gstreamer bug.

with:

    replaygain:
        backend: gstreamer
    
and:

       $ pacman -Q gstreamer
       gstreamer 1.4.5-1
    
and:

    $ beet version
    beets version 1.3.14
    plugins: bucket, check, copyartifacts, duplicates, fetchart, importadded, lastgenre, lyrics, mbsync, missing, replaygain, smartplaylist, the, web

    
I get:
    
    $ beet import ~/music
    Traceback (most recent call last):
      File "/usr/bin/beet", line 9, in <module>
        load_entry_point('beets==1.3.14', 'console_scripts', 'beet')()
      File "/usr/lib/python2.7/site-packages/beets/ui/__init__.py", line 1140, in main
        _raw_main(args)
      File "/usr/lib/python2.7/site-packages/beets/ui/__init__.py", line 1126, in _raw_main
        subcommands, plugins, lib = _setup(options, lib)
      File "/usr/lib/python2.7/site-packages/beets/ui/__init__.py", line 1005, in _setup
        plugins = _load_plugins(config)
      File "/usr/lib/python2.7/site-packages/beets/ui/__init__.py", line 991, in _load_plugins
        plugins.send("pluginload")
      File "/usr/lib/python2.7/site-packages/beets/plugins.py", line 457, in send
        for handler in event_handlers()[event]:
      File "/usr/lib/python2.7/site-packages/beets/plugins.py", line 440, in event_handlers
        for plugin in find_plugins():
      File "/usr/lib/python2.7/site-packages/beets/plugins.py", line 288, in find_plugins
        _instances[cls] = cls()
      File "/usr/lib/python2.7/site-packages/beetsplug/replaygain.py", line 791, in __init__
        self.config, self._log
      File "/usr/lib/python2.7/site-packages/beetsplug/replaygain.py", line 394, in __init__
        self._rg.set_property("forced", True)
AttributeError: 'NoneType' object has no attribute 'set_property'

**Comment by sampsyo** [comment]
Thanks for reporting. Can you check whether installing `gst-plugins-good` (which includes the `rganalysis` component) fixes this?

If it does, we should still fix the crash and print a helpful error message when the plugin is missing.

**Comment by hrehfeld** [comment]
Thanks. No way to verify if it's fixed, but it doesn't seem to occur anymore.

**Comment by sampsyo** [comment]
Thanks! I added a helpful error message.

**Comment by bharath5673** [comment]
this is due to memory error..
try:

```
    export GST_LIBS="-lgstreamer-1.0 -lgobject-2.0 -lglib-2.0"
    export GST_CFLAGS="-pthread -I/usr/include/gstreamer-1.0 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include"

```

and it will run for sure..
