### ISSUE TITLE
Beets Crashes on Import

### ISSUE THREAD

**Issue by Night-Man** [sampsyo/beets#1546]
Every time I run beets import it crashes and gives me this error

````
Traceback (most recent call last):
  File "/usr/local/bin/beet", line 9, in <module>
    load_entry_point('beets==1.3.14', 'console_scripts', 'beet')()
  File "/usr/local/lib/python2.7/dist-packages/beets-1.3.14-py2.7.egg/beets/ui/__init__.py", line 114                                                       0, in main
    _raw_main(args)
  File "/usr/local/lib/python2.7/dist-packages/beets-1.3.14-py2.7.egg/beets/ui/__init__.py", line 113                                                       0, in _raw_main
    subcommand.func(lib, suboptions, subargs)
  File "/usr/local/lib/python2.7/dist-packages/beets-1.3.14-py2.7.egg/beets/ui/commands.py", line 881                                                       , in import_func
    import_files(lib, paths, query)
  File "/usr/local/lib/python2.7/dist-packages/beets-1.3.14-py2.7.egg/beets/ui/commands.py", line 858                                                       , in import_files
    session.run()
  File "/usr/local/lib/python2.7/dist-packages/beets-1.3.14-py2.7.egg/beets/importer.py", line 316, i                                                       n run
    pl.run_parallel(QUEUE_SIZE)
  File "/usr/local/lib/python2.7/dist-packages/beets-1.3.14-py2.7.egg/beets/util/pipeline.py", line 3                                                       47, in run
    self.coro.send(msg)
  File "/usr/local/lib/python2.7/dist-packages/beets-1.3.14-py2.7.egg/beets/util/pipeline.py", line 1                                                       60, in coro
    task = func(*(args + (task,)))
  File "/usr/local/lib/python2.7/dist-packages/beets-1.3.14-py2.7.egg/beets/importer.py", line 1380,                                                        in manipulate_files
    task.finalize(session)
  File "/usr/local/lib/python2.7/dist-packages/beets-1.3.14-py2.7.egg/beets/importer.py", line 537, i                                                       n finalize
    self._emit_imported(session.lib)
  File "/usr/local/lib/python2.7/dist-packages/beets-1.3.14-py2.7.egg/beets/importer.py", line 563, i                                                       n _emit_imported
    plugins.send('album_imported', lib=lib, album=self.album)
  File "/usr/local/lib/python2.7/dist-packages/beets-1.3.14-py2.7.egg/beets/plugins.py", line 458, in                                                        send
    result = handler(**arguments)
  File "/usr/local/lib/python2.7/dist-packages/beets-1.3.14-py2.7.egg/beets/plugins.py", line 123, in                                                        wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/beets-1.3.14-py2.7.egg/beetsplug/importadded.py", line                                                        109, in update_album_times
    album.added = min(album_mtimes)
ValueError: min() arg is an empty sequence
````

Here's the config.yaml
````
directory: /media/media/music/New/Imported
library: /media/media/music/Music/musiclibrary.blb

import:
    copy: yes
    move: no
    log: /home/media/apps/beets/beets.log

plugins: lyrics chroma lastgenre lastimport fetchart ftintitle fromfilename inline web copyartifacts rewrite discogs importadded replaygain rewrite importfeeds mpdupdate plexupdate smartplaylist duplicates fuzzy info mbcollection missing types check follow

paths:
    default: $albumartist_sort/($original_year) $album%aunique{} ($year) [$format]/%if{$multidisc,Disc $disc/}$track. $title
    singleton: Non-Album/$artist/$title
    comp: Compilations/$album%aunique{}/$track $title
    albumtype:soundtrack: Soundtracks/$album/$track $title
    ext:log: $albumartist - $album
    ext:cue: $albumartist - $album

item_fields:
    multidisc: 1 if disctotal > 1 else 0

original_date: no

match:
    preferred:
        countries: ['US', 'GB|UK']
        media: ['CD', 'Digital Media|File']
        original_year: yes

lyrics:
    auto: yes
    fallback: 'No lyrics found'
    force: no
    google_API_key: ********
    google_engine_ID: 009217259823014548361:lndtuqkycfu
    sources: google lyricwiki lyrics.com musixmatch

chroma:
    auto: yes

acoustid:
    apikey: ********

lastgenre:
    auto: yes
    canonical: yes
    count: 1
    fallback: ''
    force: yes
    min_weight: 10
    source: artist
    separator: ', '
    whitelist: yes

copyartifacts:
    extensions: .*
    print_ignored: yes

echonest:
    apikey: ********
    auto: yes
    upload: yes
    convert: yes
    truncate: yes

fetchart:
    auto: yes
    cautious: yes
    cover_names: cover front art album folder
    google_search: no
    minwidth: 0
    enforce_ratio: no
    remote_priority: no
    sources: coverart itunes albumart amazon google wikipedia

ftintitle:
    auto: yes
    drop: no
    format: feat. {0}

importadded:
    preserve_mtimes: no

lastimport:
    user: ********
    per_page: 500
    retry_limit: 3

mpd:
    host: localhost
    port: 6600
    password: None
    rating: yes
    rating_mix: 0.75

replaygain:
    auto: yes
    backend: gstreamer
    overwrite: yes
    targetlevel: 89    

importfeeds:
    absolute_path: yes
    dir: /media/media/music/Playlists/
    fortmats: m3u_multi
    m3u_name: New\ Music.m3u
    relative_to: /media/media/music/Music/

plex:
    host: localhost
    port: ********

duplicates:
    album: no
    checksum: ffmpeg -i {file} -f crc -
    copy: none
    count: no
    delete: no
    format: $albumartist - $album - $title
    full: no
    strict: no
    keys: [mb_trackid, mb_albumid]
    move: none
    path: no
    tag: no

fuzzy:
    threshold: 0.7
    prefix: '~'

musicbrainz:
    user: ********
    pass:********

mbcollection:
    auto: yes

missing:
    count: yes
    format: $albumartist - $album - $title
    total: yes

types:
    rating: int

web:
    host: 127.0.0.1
    port: 8337
    
check:
  import: yes
  write-check: yes
  write-update: yes
  convert-update: yes
  threads: 4

follow:
    email: ********
    password: ********
    userid: ********
    auto: yes
````

Ubuntu 14.04

**Comment by sampsyo** [comment]
Thanks for the report, and sorry for the frustrating crash.

The error is coming from the `importadded` plugin. Can you check (on a lark) whether flipping that `preserve_mtimes` option has any effect?

Also, does this happen regardless of which album you import? And does it happen before it prompts you for any input?

**Comment by Night-Man** [comment]
It would prompt me for input for several albums when I was importing new things, but in this specific case that I posted the log from i was using
````
beet import -AC /path/to/library
````
to import my current library so it wasn't prompting me at all. It didn't happen on the same album but usually about 40 albums into an import -AC and only 5 or 6 in on an auto tagging import, so it may be a time thing.

I flipped the preserve_mtimes to yes, and it seemed to get a little further. but got the same error.

Then I removed importadded from the plugins line and got this;

````
/media/media/music/Music/Beastie Boys/Paul's Boutique Demos (Bootleg) (2005) [FL                                                                     AC]
/media/media/music/Music/Beastie Boys/Paul’s Boutique (1989) [FLAC]
Ignored files:
    1 - Cover.jpg
    2 - Back.jpg
    3 - Disc.jpg
    Matched Artwork.jpg
/media/media/music/Music/Beastie Boys/Root Down (EP) (1995) [FLAC]
/media/media/music/Music/Beastie Boys/So What'cha Want (Single) (1992) [FLAC]
/media/media/music/Music/Beastie Boys/The In Sound From Way Out! (Insrumental An                                                                     thology) (1996) [FLAC]
Followed A Silent Film
/media/media/music/Music/Beastie Boys/The Mix-Up (2007) [FLAC]
/media/media/music/Music/Beastie Boys/To the 5 Boroughs (2004) [FLAC]
/media/media/music/Music/Beastie Boys/Tour Shot! (EP) (1994) [FLAC]
/media/media/music/Music/Beastie Boys/Ultra Fly Tracks (Bootleg) (1994) [FLAC]
/media/media/music/Music/Beat, The/I Just Can’t Stop It (1980) [FLAC]
/media/media/music/Music/Beat, The/Special Beat Service (1982) [FLAC]
Traceback (most recent call last):
  File "/usr/local/bin/beet", line 9, in <module>
    load_entry_point('beets==1.3.14', 'console_scripts', 'beet')()
  File "/usr/local/lib/python2.7/dist-packages/beets-1.3.14-py2.7.egg/beets/ui/_                                                                     _init__.py", line 1140, in main
    _raw_main(args)
  File "/usr/local/lib/python2.7/dist-packages/beets-1.3.14-py2.7.egg/beets/ui/_                                                                     _init__.py", line 1130, in _raw_main
    subcommand.func(lib, suboptions, subargs)
  File "/usr/local/lib/python2.7/dist-packages/beets-1.3.14-py2.7.egg/beets/ui/c                                                                     ommands.py", line 881, in import_func
    import_files(lib, paths, query)
  File "/usr/local/lib/python2.7/dist-packages/beets-1.3.14-py2.7.egg/beets/ui/c                                                                     ommands.py", line 858, in import_files
    session.run()
  File "/usr/local/lib/python2.7/dist-packages/beets-1.3.14-py2.7.egg/beets/impo                                                                     rter.py", line 316, in run
    pl.run_parallel(QUEUE_SIZE)
  File "/usr/local/lib/python2.7/dist-packages/beets-1.3.14-py2.7.egg/beets/util                                                                     /pipeline.py", line 301, in run
    out = self.coro.send(msg)
  File "/usr/local/lib/python2.7/dist-packages/beets-1.3.14-py2.7.egg/beets/util                                                                     /pipeline.py", line 183, in coro
    func(*(args + (task,)))
  File "/usr/local/lib/python2.7/dist-packages/beets-1.3.14-py2.7.egg/beets/impo                                                                     rter.py", line 1353, in plugin_stage
    func(session, task)
  File "/usr/local/lib/python2.7/dist-packages/beets-1.3.14-py2.7.egg/beets/plug                                                                     ins.py", line 117, in wrapper
    assert self._log.level == logging.NOTSET
AssertionError
````

**Comment by Night-Man** [comment]
Actually I added importadded back to the plugins line and ran import -AC and got that same AssertionError, so I don't know what's going on.

**Comment by sampsyo** [comment]
Does this seem to be associated with a specific album? Can you reproduce it by importing the same album again?

**Comment by Night-Man** [comment]
No, but it does do it after a consistent average of albums number, Beastie Boys, Beck, etc. around 40-45 albums for an import -AC import.

But then it crashes after only seven or eight albums during a normal autotagging import as seen here

````
media@mediaserver:~/scripts$ beet -c ~/.config/beets/import_config.yaml import -q /media/media/music/New/Manual

/media/media/music/New/Manual (1 items)
Skipping.

/media/media/music/New/Manual/Black Rebel Motorcycle Club - 2001 - Sampler (4 items)
Skipping.

/media/media/music/New/Manual/Black Rebel Motorcycle Club - 2001 - Screaming Gun [FLAC] (5 items)
Tagging:
    Black Rebel Motorcycle Club - Screaming Gun
URL:
    http://musicbrainz.org/release/0505714a-c90f-4501-8339-1db9e7aff9d9
(Similarity: 96.9%) (tracks) (2001, US)
 * Failsafe                 -> Fail-Safe
 * TV Loop (Deep Down) (#5) -> TV Loop (Down Deep) (#4) (index, title)
 * Screaming Gun (#4)       -> Screaming Gun (#5) (index)

/media/media/music/New/Manual/Black Rebel Motorcycle Club - Beat The Devil's Tattoo (2010) [FLAC] (VVR730519) (15 items)
Correcting tags from:
    Black Rebel Motorcycle Club - Beat The Devil's Tattoo
To:
    Black Rebel Motorcycle Club - Beat the Devil’s Tattoo
URL:
    http://musicbrainz.org/release/2be4297a-4afd-436b-9afd-95cc326ab950
(Similarity: 99.4%) (country) (CD, 2010, GB, Abstract Dragon)
 * Beat The Devil's Tattoo -> Beat the Devil’s Tattoo
 * Shadow's Keeper         -> Shadow’s Keeper
 * Half-State              -> Half‐State
 * 1-51                    -> 1:51
Moving artifact: Black Rebel Motorcycle Club - Screaming Gun.log
Moving artifact: Black Rebel Motorcycle Club - Screaming Gun.m3u
Moving artifact: Black Rebel Motorcycle Club - Screaming Gun.cue
Followed Black Rebel Motorcycle Club

/media/media/music/New/Manual/Black Rebel Motorcycle Club - Beat The Devil's Tattoo - 2010 (CD - FLAC - Lossless) (13 items)
Correcting tags from:
    Black Rebel Motorcycle Club - Beat The Devil's Tattoo
To:
    Black Rebel Motorcycle Club - Beat the Devil’s Tattoo
URL:
    http://musicbrainz.org/release/fdf5cdda-a94f-49f6-9f8a-80f56f3e7c59
(Similarity: 100.0%) (CD, 2010, US, Vagrant Records)
 * Beat The Devil's Tattoo -> Beat the Devil’s Tattoo
 * Shadow's Keeper         -> Shadow’s Keeper
 * Half State              -> Half-State
This album is already in the library!
Skipping.

/media/media/music/New/Manual/Black Rebel Motorcycle Club - iTunes Session (2010) [iTunes Plus] (7 items)
Skipping.

/media/media/music/New/Manual/Black Rebel Motorcycle Club - Specter at the Feast (12 items)
Tagging:
    Black Rebel Motorcycle Club - Specter at the Feast
URL:
    http://musicbrainz.org/release/aca722b8-341c-4227-a169-7cad4b40da0d
(Similarity: 100.0%) (CD, 2013, US)
 * Let The Day Begin   -> Let the Day Begin
 * Hate The Taste      -> Hate the Taste
 * Sometimes The Light -> Sometimes the Light

/media/media/music/New/Manual/Black Rebel Motorcycle Club - The Effects of 333 - 2008 (WEB FLAC) (10 items)
Correcting tags from:
    Black Rebel Motorcycle Club - The Effects Of 333
To:
    Black Rebel Motorcycle Club - The Effects of 333
URL:
    http://musicbrainz.org/release/12129186-c087-4a5c-aafe-ef016e5789b2
(Similarity: 98.2%) (media) (Digital Media, 2008, US, Abstract Dragon)
 * The Effects Of 333     -> The Effects of 333
 * I Know You're In There -> I Know You’re in There
Moving artifact: Black Rebel Motorcycle Club - Beat the Devil’s Tattoo.cue
Moving artifact: Black Rebel Motorcycle Club - Beat the Devil’s Tattoo.log
Moving artifact: Black Rebel Motorcycle Club - Beat The Devil's Tattoo.m3u
Traceback (most recent call last):
  File "/usr/local/bin/beet", line 9, in <module>
    load_entry_point('beets==1.3.14', 'console_scripts', 'beet')()
  File "/usr/local/lib/python2.7/dist-packages/beets-1.3.14-py2.7.egg/beets/ui/__init__.py", line 1140, in main
    _raw_main(args)
  File "/usr/local/lib/python2.7/dist-packages/beets-1.3.14-py2.7.egg/beets/ui/__init__.py", line 1130, in _raw_main
    subcommand.func(lib, suboptions, subargs)
  File "/usr/local/lib/python2.7/dist-packages/beets-1.3.14-py2.7.egg/beets/ui/commands.py", line 881, in import_func
    import_files(lib, paths, query)
  File "/usr/local/lib/python2.7/dist-packages/beets-1.3.14-py2.7.egg/beets/ui/commands.py", line 858, in import_files
    session.run()
  File "/usr/local/lib/python2.7/dist-packages/beets-1.3.14-py2.7.egg/beets/importer.py", line 316, in run
    pl.run_parallel(QUEUE_SIZE)
  File "/usr/local/lib/python2.7/dist-packages/beets-1.3.14-py2.7.egg/beets/util/pipeline.py", line 301, in run
    out = self.coro.send(msg)
  File "/usr/local/lib/python2.7/dist-packages/beets-1.3.14-py2.7.egg/beets/util/pipeline.py", line 160, in coro
    task = func(*(args + (task,)))
  File "/usr/local/lib/python2.7/dist-packages/beets-1.3.14-py2.7.egg/beets/importer.py", line 1268, in user_query
    plugins.send('import_task_choice', session=session, task=task)
  File "/usr/local/lib/python2.7/dist-packages/beets-1.3.14-py2.7.egg/beets/plugins.py", line 458, in send
    result = handler(**arguments)
  File "/usr/local/lib/python2.7/dist-packages/beets-1.3.14-py2.7.egg/beets/plugins.py", line 117, in wrapper
    assert self._log.level == logging.NOTSET
AssertionError
````

It's happening even without the importadded plugin enabled on the plugins line.

Sorry my config.yaml is so large, I like to type out all the options so I can remember what they are easily.

**Comment by Night-Man** [comment]
FYI, also that import_config.yaml used on that last log I posted is exactly the same except for the directories and libraries.

**Comment by sampsyo** [comment]
This is actually a different error (see the bottom of the traceback blob). Has the original one recurred?

Have you tried narrowing down which plugin is causing the new error? We've had reports that the third-party copyartifacts can cause crashes like this.

**Comment by Night-Man** [comment]
OK, I'll try to narrow it down.

I disabled copyartifacts and got this
````
/media/media/music/Music/Big Pink, The/A Brief History of Love (2009) [FLAC]
/media/media/music/Music/Billy Boy on Poison/Drama Junkie Queen (2009) [FLAC]
/media/media/music/Music/BIlly Bragg/Back to Basics (Anthology) (1987) [FLAC]
/media/media/music/Music/BIlly Bragg/Don't Try This at Home (Bonus Disc) (1991) [FLAC]; /media/media/music/Music/BIlly Bragg/Don't Try This at Home (Bonus Disc) (1991) [FLAC]/Disc 01; /media/media/music/Music/BIlly Bragg/Don't Try This at Home (Bonus Disc) (1991) [FLAC]/Disc 02
/media/media/music/Music/BIlly Bragg/Talking With the Taxman About Poetry [1986] (1986) [FLAC]; /media/media/music/Music/BIlly Bragg/Talking With the Taxman About Poetry [1986] (1986) [FLAC]/Disc 01; /media/media/music/Music/BIlly Bragg/Talking With the Taxman About Poetry [1986] (1986) [FLAC]/Disc 02
/media/media/music/Music/BIlly Bragg/William Bloke (1996) [FLAC]; /media/media/music/Music/BIlly Bragg/William Bloke (1996) [FLAC]/Disc 01; /media/media/music/Music/BIlly Bragg/William Bloke (1996) [FLAC]/Disc 02
/media/media/music/Music/BIlly Bragg/Workers Playtime (1988) [FLAC]; /media/media/music/Music/BIlly Bragg/Workers Playtime (1988) [FLAC]/Disc 01; /media/media/music/Music/BIlly Bragg/Workers Playtime (1988) [FLAC]/Disc 02
/media/media/music/Music/Billy Bragg and The Blokes/England, Half English (Bonus Disc) (2002) [FLAC]; /media/media/music/Music/Billy Bragg and The Blokes/England, Half English (Bonus Disc) (2002) [FLAC]/Disc 01; /media/media/music/Music/Billy Bragg and The Blokes/England, Half English (Bonus Disc) (2002) [FLAC]/Disc 02
Followed A Tribe Called Quest
Traceback (most recent call last):
  File "/usr/local/bin/beet", line 9, in <module>
    load_entry_point('beets==1.3.14', 'console_scripts', 'beet')()
  File "/usr/local/lib/python2.7/dist-packages/beets-1.3.14-py2.7.egg/beets/ui/__init__.py", line 1140, in main
    _raw_main(args)
  File "/usr/local/lib/python2.7/dist-packages/beets-1.3.14-py2.7.egg/beets/ui/__init__.py", line 1130, in _raw_main
    subcommand.func(lib, suboptions, subargs)
  File "/usr/local/lib/python2.7/dist-packages/beets-1.3.14-py2.7.egg/beets/ui/commands.py", line 881, in import_func
    import_files(lib, paths, query)
  File "/usr/local/lib/python2.7/dist-packages/beets-1.3.14-py2.7.egg/beets/ui/commands.py", line 858, in import_files
    session.run()
  File "/usr/local/lib/python2.7/dist-packages/beets-1.3.14-py2.7.egg/beets/importer.py", line 316, in run
    pl.run_parallel(QUEUE_SIZE)
  File "/usr/local/lib/python2.7/dist-packages/beets-1.3.14-py2.7.egg/beets/util/pipeline.py", line 301, in run
    out = self.coro.send(msg)
  File "/usr/local/lib/python2.7/dist-packages/beets-1.3.14-py2.7.egg/beets/util/pipeline.py", line 183, in coro
    func(*(args + (task,)))
  File "/usr/local/lib/python2.7/dist-packages/beets-1.3.14-py2.7.egg/beets/importer.py", line 1353, in plugin_stage
    func(session, task)
  File "/usr/local/lib/python2.7/dist-packages/beets-1.3.14-py2.7.egg/beets/plugins.py", line 117, in wrapper
    assert self._log.level == logging.NOTSET
AssertionError
````

With copyartifacts enabled, importadded enabled, preserve_mtimes set to yes
````
/media/media/music/Music/Big D and the Kids Table/How It Goes (2004) [FLAC]
/media/media/music/Music/Big D and the Kids Table/Strictly Rude (2007) [FLAC]
/media/media/music/Music/Big Data/1.0 (EP) (2013) [MP3]
/media/media/music/Music/Big Pink, The/A Brief History of Love (2009) [FLAC]
/media/media/music/Music/Billy Boy on Poison/Drama Junkie Queen (2009) [FLAC]
Ignored files:
    1 - Cover.jpg
    10 - Booklet 8.jpg
    11 - Booklet 9.jpg
    12 - Booklet 10.jpg
    13 - Alternate Back.jpg
    2 - Back.jpg
    3 - Booklet 1.jpg
    4 - Booklet 2.jpg
    5 - Booklet 3.jpg
    6 - Booklet 4.jpg
    7 - Booklet 5.jpg
    8 - Booklet 6.jpg
    9 - Booklet 7.jpg
    Unmatched Artwork.jpg
/media/media/music/Music/BIlly Bragg/Back to Basics (Anthology) (1987) [FLAC]
Traceback (most recent call last):
  File "/usr/local/bin/beet", line 9, in <module>
    load_entry_point('beets==1.3.14', 'console_scripts', 'beet')()
  File "/usr/local/lib/python2.7/dist-packages/beets-1.3.14-py2.7.egg/beets/ui/__init__.py", line 1140, in main
    _raw_main(args)
  File "/usr/local/lib/python2.7/dist-packages/beets-1.3.14-py2.7.egg/beets/ui/__init__.py", line 1130, in _raw_main
    subcommand.func(lib, suboptions, subargs)
  File "/usr/local/lib/python2.7/dist-packages/beets-1.3.14-py2.7.egg/beets/ui/commands.py", line 881, in import_func
    import_files(lib, paths, query)
  File "/usr/local/lib/python2.7/dist-packages/beets-1.3.14-py2.7.egg/beets/ui/commands.py", line 858, in import_files
    session.run()
  File "/usr/local/lib/python2.7/dist-packages/beets-1.3.14-py2.7.egg/beets/importer.py", line 316, in run
    pl.run_parallel(QUEUE_SIZE)
  File "/usr/local/lib/python2.7/dist-packages/beets-1.3.14-py2.7.egg/beets/util/pipeline.py", line 301, in run
    out = self.coro.send(msg)
  File "/usr/local/lib/python2.7/dist-packages/beets-1.3.14-py2.7.egg/beets/util/pipeline.py", line 183, in coro
    func(*(args + (task,)))
  File "/usr/local/lib/python2.7/dist-packages/beets-1.3.14-py2.7.egg/beets/importer.py", line 1353, in plugin_stage
    func(session, task)
  File "/usr/local/lib/python2.7/dist-packages/beets-1.3.14-py2.7.egg/beets/plugins.py", line 117, in wrapper
    assert self._log.level == logging.NOTSET
AssertionError
````

copyartifacts enabled, importadded enabled, preserve_mtimes no
````
/media/media/music/Music/Blur/For Tomorrow (1993) [FLAC]
/media/media/music/Music/Blur/Leisure (1991) [FLAC]
/media/media/music/Music/Blur/M.O.R. (1997) [FLAC]
Traceback (most recent call last):
  File "/usr/local/bin/beet", line 9, in <module>
    load_entry_point('beets==1.3.14', 'console_scripts', 'beet')()
  File "/usr/local/lib/python2.7/dist-packages/beets-1.3.14-py2.7.egg/beets/ui/__init__.py", line 1140, in main
    _raw_main(args)
  File "/usr/local/lib/python2.7/dist-packages/beets-1.3.14-py2.7.egg/beets/ui/__init__.py", line 1130, in _raw_main
    subcommand.func(lib, suboptions, subargs)
  File "/usr/local/lib/python2.7/dist-packages/beets-1.3.14-py2.7.egg/beets/ui/commands.py", line 881, in import_func
    import_files(lib, paths, query)
  File "/usr/local/lib/python2.7/dist-packages/beets-1.3.14-py2.7.egg/beets/ui/commands.py", line 858, in import_files
    session.run()
  File "/usr/local/lib/python2.7/dist-packages/beets-1.3.14-py2.7.egg/beets/importer.py", line 316, in run
    pl.run_parallel(QUEUE_SIZE)
  File "/usr/local/lib/python2.7/dist-packages/beets-1.3.14-py2.7.egg/beets/util/pipeline.py", line 301, in run
    out = self.coro.send(msg)
  File "/usr/local/lib/python2.7/dist-packages/beets-1.3.14-py2.7.egg/beets/util/pipeline.py", line 183, in coro
    func(*(args + (task,)))
  File "/usr/local/lib/python2.7/dist-packages/beets-1.3.14-py2.7.egg/beets/importer.py", line 1353, in plugin_stage
    func(session, task)
  File "/usr/local/lib/python2.7/dist-packages/beets-1.3.14-py2.7.egg/beets/plugins.py", line 117, in wrapper
    assert self._log.level == logging.NOTSET
AssertionError
````

It seems I'm not even getting that original ValueError: min() arg is an empty sequence

**Comment by Night-Man** [comment]
Anything else I should try? I might have time a little later to try toggling off a bunch of plugins one at a time, but if you have suggestions to narrow it down that'd be great.

**Comment by sampsyo** [comment]
OK, thanks for looking into it. It sounds like copyartifacts is not the cause then—but I would still try fiddling with third-party plugins first. For example, my first stop would be `check`, then `follow`.

**Comment by Ho33e5** [comment]
Just to bump this issue, i got the exact same traceback. For info I also have the `check` plugin enabled, it may be that (besides that i only have `discogs` and `info`).

**Comment by sampsyo** [comment]
@Ho33e5, can you help by narrowing it down to be certain that it's `check`? Or otherwise help us reproduce the problem?

**Comment by Ho33e5** [comment]
Sure, I disabled the `check` plugin and it seems that this crash doesn't occur anymore. But I can't really reproduce the crash reliably, it is not on particular albums, it occurs on big import, something like every 20-30 imports.

**Comment by sampsyo** [comment]
Strange. Maybe it would be a good idea to report the bug to the beets-check project.

**Comment by sampsyo** [comment]
It looks like this was the `beets-check` bug reported elsewhere.
