### ISSUE TITLE
UnicodeDecodeError while importing non ASCII album

### ISSUE THREAD

**Issue by raymondwanyoike** [sampsyo/beets#1557]
Looks like the permission plugin isn't handling UTF-8? Paths like `.../菅野祐悟/ALBUM/...`

```
Traceback (most recent call last):
  File "/usr/bin/beet", line 9, in <module>
    load_entry_point('beets==1.3.13', 'console_scripts', 'beet')()
  File "/usr/lib/python2.7/site-packages/beets/ui/__init__.py", line 1104, in main
    _raw_main(args)
  File "/usr/lib/python2.7/site-packages/beets/ui/__init__.py", line 1094, in _raw_main
    subcommand.func(lib, suboptions, subargs)
  File "/usr/lib/python2.7/site-packages/beets/ui/commands.py", line 893, in import_func
    import_files(lib, paths, query)
  File "/usr/lib/python2.7/site-packages/beets/ui/commands.py", line 870, in import_files
    session.run()
  File "/usr/lib/python2.7/site-packages/beets/importer.py", line 316, in run
    pl.run_parallel(QUEUE_SIZE)
  File "/usr/lib/python2.7/site-packages/beets/util/pipeline.py", line 347, in run
    self.coro.send(msg)
  File "/usr/lib/python2.7/site-packages/beets/util/pipeline.py", line 160, in coro
    task = func(*(args + (task,)))
  File "/usr/lib/python2.7/site-packages/beets/importer.py", line 1370, in manipulate_files
    task.finalize(session)
  File "/usr/lib/python2.7/site-packages/beets/importer.py", line 517, in finalize
    self._emit_imported(session.lib)
  File "/usr/lib/python2.7/site-packages/beets/importer.py", line 547, in _emit_imported
    plugins.send('album_imported', lib=lib, album=self.album)
  File "/usr/lib/python2.7/site-packages/beets/plugins.py", line 455, in send
    result = handler(**arguments)
  File "/usr/lib/python2.7/site-packages/beets/plugins.py", line 123, in wrapper
    return func(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/beetsplug/permissions.py", line 90, in permissions
    path))
  File "/usr/lib/python2.7/site-packages/beetsplug/permissions.py", line 38, in dirs_in_library
    if ancestor.startswith(library)][1:]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe8 in position 36: ordinal not in range(128)
```

**Comment by raymondwanyoike** [comment]
Fixed in v1.3.14, duplicate of #1449
