### ISSUE TITLE
Importing fails on a file

### ISSUE THREAD

**Issue by bearcatsandor** [sampsyo/beets#1564]
I'm trying to import a directory with 100 songs in it as singletons. My command beet import -s ./  fails on a particular track. I'm using the git version of Beets pulled on 8/7/2015

What i see is:

/home/hometheater/audio/various_artists/rs500-flac/101-200/154-buddy_holly_&_the_crickets-rave_on_1958.wv
Tagging track: Buddy Holly & The Crickets - Rave On
URL:
    http://musicbrainz.org/recording/ce146f18-96bc-4ee6-a534-61910db2892a
(Similarity: 100.0%)
[A]pply, More candidates, Skip, Use as-is, Enter search, enter Id, aBort? 

/home/hometheater/audio/various_artists/rs500-flac/101-200/157-the_flamingos-i_only_have_eyes_for_you_1959.wv
Correcting track tags from:
    The Flamingos - I Only Have Eyes For You
To:
    The Flamingos - I Only Have Eyes for You
URL:
    http://musicbrainz.org/recording/4ebfa4d9-d36f-437a-846f-2f908828cdb1
(Similarity: 100.0%)
[A]pply, More candidates, Skip, Use as-is, Enter search, enter Id, aBort? 
Traceback (most recent call last):
  File "/usr/lib/python-exec/python2.7/beet", line 9, in <module>
    load_entry_point('beets==1.3.15', 'console_scripts', 'beet')()
  File "/usr/lib64/python2.7/site-packages/beets/ui/__init__.py", line 1161, in main
    _raw_main(args)
  File "/usr/lib64/python2.7/site-packages/beets/ui/__init__.py", line 1151, in _raw_main
    subcommand.func(lib, suboptions, subargs)
  File "/usr/lib64/python2.7/site-packages/beets/ui/commands.py", line 875, in import_func
    import_files(lib, paths, query)
  File "/usr/lib64/python2.7/site-packages/beets/ui/commands.py", line 852, in import_files
    session.run()
  File "/usr/lib64/python2.7/site-packages/beets/importer.py", line 316, in run
    pl.run_parallel(QUEUE_SIZE)
  File "/usr/lib64/python2.7/site-packages/beets/util/pipeline.py", line 301, in run
    out = self.coro.send(msg)
  File "/usr/lib64/python2.7/site-packages/beets/util/pipeline.py", line 183, in coro
    func(*(args + (task,)))
  File "/usr/lib64/python2.7/site-packages/beets/importer.py", line 1353, in plugin_stage
    func(session, task)
  File "/usr/lib64/python2.7/site-packages/beets/plugins.py", line 123, in wrapper
    return func(*args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/beetsplug/lastgenre/__init__.py", line 381, in imported
    item.genre, src = self._get_genre(item)
  File "/usr/lib64/python2.7/site-packages/beetsplug/lastgenre/__init__.py", line 280, in _get_genre
    result = self.fetch_track_genre(obj)
  File "/usr/lib64/python2.7/site-packages/beetsplug/lastgenre/__init__.py", line 259, in fetch_track_genre
    obj.title)
  File "/usr/lib64/python2.7/site-packages/beetsplug/lastgenre/__init__.py", line 234, in _last_lookup
    genre = self.fetch_genre(method(*args_replaced))
  File "/usr/lib64/python2.7/site-packages/beetsplug/lastgenre/__init__.py", line 198, in fetch_genre
    return self._resolve_genres(self._tags_for(lastfm_obj, min_weight))
  File "/usr/lib64/python2.7/site-packages/beetsplug/lastgenre/__init__.py", line 414, in _tags_for
    res = [el for el in res if (int(el.weight) or 0) >= min_weight]
TypeError: int() argument must be a string or a number, not 'NoneType'

It may be track 157 or 158, but i don't know what tag to clobber to make it pass.

Adrian responded: 
Thanks for the report—this seems to be a bug introduced by a "fix" in the most recent version. Can you please file an issue on GitHub?

**Comment by sampsyo** [comment]
This is a regression introduced by #1559, which apparently did not anticipate `el.weight` being None. I'll fix it now.

**Comment by sampsyo** [comment]
Fix pushed. Could you check whether that in fact makes the error go away?

**Comment by bearcatsandor** [comment]
It does seem to solve that error. Thank you. Now i get a gst error which may be unrelated, so i'm closing this one.
