### ISSUE TITLE
fetchart: fails

### ISSUE THREAD

**Issue by Kolbasz12** [sampsyo/beets#1581]
Not sure if this relates to the other posted issue, but I removed google from my fetchart config and still got the error, so not sure if it relates or not.

Works fine most of the time, currently hanging on one album

Traceback (most recent call last):
  File "/usr/local/bin/beet", line 9, in <module>
    load_entry_point('beets==1.3.15', 'console_scripts', 'beet')()
  File "/usr/local/lib/python2.7/dist-packages/beets-1.3.15-py2.7.egg/beets/ui/_                                                  _init__.py", line 1161, in main
    _raw_main(args)
  File "/usr/local/lib/python2.7/dist-packages/beets-1.3.15-py2.7.egg/beets/ui/_                                                  _init__.py", line 1151, in _raw_main
    subcommand.func(lib, suboptions, subargs)
  File "/usr/local/lib/python2.7/dist-packages/beets-1.3.15-py2.7.egg/beets/ui/c                                                  ommands.py", line 875, in import_func
    import_files(lib, paths, query)
  File "/usr/local/lib/python2.7/dist-packages/beets-1.3.15-py2.7.egg/beets/ui/c                                                  ommands.py", line 852, in import_files
    session.run()
  File "/usr/local/lib/python2.7/dist-packages/beets-1.3.15-py2.7.egg/beets/impo                                                  rter.py", line 316, in run
    pl.run_parallel(QUEUE_SIZE)
  File "/usr/local/lib/python2.7/dist-packages/beets-1.3.15-py2.7.egg/beets/util                                                  /pipeline.py", line 301, in run
    out = self.coro.send(msg)
  File "/usr/local/lib/python2.7/dist-packages/beets-1.3.15-py2.7.egg/beets/util                                                  /pipeline.py", line 183, in coro
    func(*(args + (task,)))
  File "/usr/local/lib/python2.7/dist-packages/beets-1.3.15-py2.7.egg/beets/impo                                                  rter.py", line 1353, in plugin_stage
    func(session, task)
  File "/usr/local/lib/python2.7/dist-packages/beets-1.3.15-py2.7.egg/beets/plug                                                  ins.py", line 123, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/beets-1.3.15-py2.7.egg/beetsplug/                                                  fetchart.py", line 385, in fetch_art
    path = self.art_for_album(task.album, task.paths, local)
  File "/usr/local/lib/python2.7/dist-packages/beets-1.3.15-py2.7.egg/beetsplug/                                                  fetchart.py", line 487, in art_for_album
    for url in self._source_urls(album):
  File "/usr/local/lib/python2.7/dist-packages/beets-1.3.15-py2.7.egg/beetsplug/                                                  fetchart.py", line 532, in _source_urls
    for url in urls:
  File "/usr/local/lib/python2.7/dist-packages/beets-1.3.15-py2.7.egg/beetsplug/                                                  fetchart.py", line 228, in get
    lpart, rpart = cover_filename.rsplit(' .', 1)
ValueError: need more than 1 value to unpack

**Comment by sampsyo** [comment]
This is a different problem. (In the future, when you refer to another issue, please link to it by typing # followed by the issue number.)

Can you please provide more details? The FAQ has instructions on how to report a bug.

**Comment by Kolbasz12** [comment]
OK,  sorry about that.

Essentially,  I imported 90% of my library.  I have one album throwing the above error. 

I have tried different versions,  going flac to mp3,  etc thinking it is a corrupt file,  but each time the result is this error. 

The album is: 2 chainz - B.O.A.T.S. II: Me Time

**Comment by sampsyo** [comment]
Here are some of the details that bug reports need to contain:

- Which version of beets?
- What's your configuration?
- Exactly what command can we run to reproduce the problem? If that involves specific files, please provide them.

Here's more background on how to report bugs: http://adriansampson.net/blog/bugrubric.html

**Comment by Kolbasz12** [comment]
OK,  

Beets version 1.3.15 running as a docker container.  I have an older container still on 1.3.13 and it works just fine with the exact same files.

I took the said bad album, ran it on 1.3.15 that prompted this issue, it failed.  I then ran it on my beets container running 1.3.13 and it imported without issue.

I then moved the files back out and ran them in 1.3.15 and it failed again.  I wanted to make sure the files were not suddenly fixed.

As far as the configuration goes, do you mean beets in docker?  Or do you mean my actual config file?

As for the command I am running, it is the basic import command passing the folder path.  This was the method used for all my media that has been imported.

docker exec -i -t beets beet import /opt/downloads/music/

**Comment by sampsyo** [comment]
> As far as the configuration goes, do you mean beets in docker?  Or do you mean my actual config file?

Your beets configuration, please.

Can you also please paste the surrounding context in beets' output? What did the autotagger say just before this traceback?

**Comment by Kolbasz12** [comment]
verbose logging: http://pastebin.com/WvUTY8Mn

config: http://pastebin.com/ys6pMwZk

**Comment by sampsyo** [comment]
Thanks for the details! Can you check whether the above commit fixes your issue?

A caveat: It looks like dbpedia, the Wikipedia API we use, may be broken right now. I might disable the source by default because it's causing annoying timeouts.

**Comment by Kolbasz12** [comment]
How do I test the commit? Run and apt-get update type thing or something else? N00b...

**Comment by sampsyo** [comment]
Please see the FAQ on running from source.

**Comment by Kolbasz12** [comment]
ran the uninstall, then installed master:

http://pastebin.com/H3BB6wcB

**Comment by sampsyo** [comment]
Thanks, my fault! The above should fix that.

**Comment by Kolbasz12** [comment]
yep, that did it.  Updated to latest and import now worked.  Thanks!
