### ISSUE TITLE
in Play plugin :TypeError: execv() arg 2 must contain only strings

### ISSUE THREAD

**Issue by jmwatte** [sampsyo/beets#1631]
I got the latest from github as of sep 30//5:30
Iget this fro; the play plugin

```
wintersj@wintersj-MS-7797:~$ beet play alice waits
Playing 16 tracks.
Traceback (most recent call last):
  File "/usr/local/bin/beet", line 9, in <module>
    load_entry_point('beets==1.3.14', 'console_scripts', 'beet')()
  File "/usr/local/lib/python2.7/dist-packages/beets-1.3.14-py2.7.egg/beets/ui/__init__.py", line 1104, in main
    _raw_main(args)
  File "/usr/local/lib/python2.7/dist-packages/beets-1.3.14-py2.7.egg/beets/ui/__init__.py", line 1094, in _raw_main
    subcommand.func(lib, suboptions, subargs)
  File "/home/wintersj/Downloads/gitdownloads/beets/beetsplug/play.py", line 131, in play_music
    util.interactive_open(open_args, command_str)
  File "/usr/local/lib/python2.7/dist-packages/beets-1.3.14-py2.7.egg/beets/util/__init__.py", line 686, in interactive_open
    return os.execlp(*command)
  File "/usr/lib/python2.7/os.py", line 329, in execlp
    execvp(file, args)
  File "/usr/lib/python2.7/os.py", line 346, in execvp
    _execvpe(file, args)
  File "/usr/lib/python2.7/os.py", line 370, in _execvpe
    func(file, *argrest)
TypeError: execv() arg 2 must contain only strings
```

I got this in my config

```
play:
   command: /usr/bin/vlc
```

Is there anyway I can help?
thx
jm

**Comment by sampsyo** [comment]
Hmm... is there any more evidence with `beet -v play ...`?

**Comment by jmwatte** [comment]
this is with -v

wintersj@wintersj-MS-7797:~$ beet -v play tom waits time
user configuration: /home/wintersj/.config/beets/config.yaml
data directory: /home/wintersj/.config/beets
plugin paths: /home/wintersj/Downloads/gitdownloads/beets/beetsplug
Sending event: pluginload
artresizer: method is (2, (6, 8, 9))
inline: adding item field multidisc
in init Searching amazon
library database: /home/wintersj/.config/beets/library.db
library directory: /media/wintersj/bb/audio
Sending event: library_opened
Playing 53 tracks.
play: executing command: /usr/bin/vlc "/tmp/tmpyR5vlX.m3u"
play: Removing temporary playlist: /tmp/tmpyR5vlX.m3u
Traceback (most recent call last):
  File "/usr/local/bin/beet", line 9, in <module>
    load_entry_point('beets==1.3.14', 'console_scripts', 'beet')()
  File "/usr/local/lib/python2.7/dist-packages/beets-1.3.14-py2.7.egg/beets/ui/__init__.py", line 1104, in main
    _raw_main(args)
  File "/usr/local/lib/python2.7/dist-packages/beets-1.3.14-py2.7.egg/beets/ui/__init__.py", line 1094, in _raw_main
    subcommand.func(lib, suboptions, subargs)
  File "/home/wintersj/Downloads/gitdownloads/beets/beetsplug/play.py", line 131, in play_music
    util.interactive_open(open_args, command_str)
  File "/usr/local/lib/python2.7/dist-packages/beets-1.3.14-py2.7.egg/beets/util/__init__.py", line 686, in interactive_open
    return os.execlp(*command)
  File "/usr/lib/python2.7/os.py", line 329, in execlp
    execvp(file, args)
  File "/usr/lib/python2.7/os.py", line 346, in execvp
    _execvpe(file, args)
  File "/usr/lib/python2.7/os.py", line 370, in _execvpe
    func(file, *argrest)
TypeError: execv() arg 2 must contain only strings


so, not much more info.... should I put some print commands somewhere?

**Comment by sampsyo** [comment]
Yeah, strange. I can't seem to reproduce this here.

Could you please edit `beets/util/__init__.py` and, in the `interactive_open` function, put this just before the `return` statement?

    print(command)

**Comment by jmwatte** [comment]
did this in beets/util/__init__.py

def interactive_open(targets, command=None):
    """Open the files in `targets` by `exec`ing a new command. (The new
    program takes over, and Python execution ends: this does not fork a
    subprocess.)

    If `command` is provided, use it. Otherwise, use an OS-specific
    command (from `open_anything`) to open the file.

    Can raise `OSError`.
    """
    if command:
        command = command.encode('utf8')
        try:
            command = [c.decode('utf8')
                       for c in shlex.split(command)]
        except ValueError:  # Malformed shell tokens.
            command = [command]
        command.insert(0, command[0])  # for argv[0]
    else:
        base_cmd = open_anything()
        command = [base_cmd, base_cmd]

    command += targets
    print(command)
    return os.execlp(*command)

and got this as a result

wintersj@wintersj-MS-7797:~$ beet play tom waits alice
Playing 16 tracks.
Traceback (most recent call last):
  File "/usr/local/bin/beet", line 9, in <module>
    load_entry_point('beets==1.3.14', 'console_scripts', 'beet')()
  File "/usr/local/lib/python2.7/dist-packages/beets-1.3.14-py2.7.egg/beets/ui/__init__.py", line 1104, in main
    _raw_main(args)
  File "/usr/local/lib/python2.7/dist-packages/beets-1.3.14-py2.7.egg/beets/ui/__init__.py", line 1094, in _raw_main
    subcommand.func(lib, suboptions, subargs)
  File "/home/wintersj/Downloads/gitdownloads/beets/beetsplug/play.py", line 130, in play_music
    util.interactive_open(open_args, command_str)
  File "/usr/local/lib/python2.7/dist-packages/beets-1.3.14-py2.7.egg/beets/util/__init__.py", line 686, in interactive_open
    return os.execlp(*command)
  File "/usr/lib/python2.7/os.py", line 329, in execlp
    execvp(file, args)
  File "/usr/lib/python2.7/os.py", line 346, in execvp
    _execvpe(file, args)
  File "/usr/lib/python2.7/os.py", line 370, in _execvpe
    func(file, *argrest)
TypeError: execv() arg 2 must contain only strings


strange

**Comment by sampsyo** [comment]
So the output didn't fire. It looks like the line in `util/__init__.py` is the same in this traceback. Are you sure you edited the right file, for the version of beets you actually have installed?

**Comment by jmwatte** [comment]
Ok,
 my bad.
I thought I was running my git version but I seem to be having a beet in usr/local/bin 

this :

#!/usr/bin/python
# EASY-INSTALL-ENTRY-SCRIPT: 'beets==1.3.14','console_scripts','beet'
__requires__ = 'beets==1.3.14'
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.exit(
        load_entry_point('beets==1.3.14', 'console_scripts', 'beet')()
    )
So I pip uninstall beets and reinstalled beets 1.3.15 and it works like it should,,,
Mea Culpa, mea maxima culpa
So close it and forget it.
Sorry
jm

**Comment by sampsyo** [comment]
Great news! :smiley:
