### ISSUE TITLE
plexupdate plugin crashed

### ISSUE THREAD

**Issue by Nerten** [sampsyo/beets#1649]
Every time after import plexupdate plugin crashed with this error:
```
Traceback (most recent call last):
  File "/usr/local/bin/beet", line 9, in <module>
    load_entry_point('beets==1.3.15', 'console_scripts', 'beet')()
  File "/usr/local/lib/python2.7/dist-packages/beets/ui/__init__.py", line 1163, in main
    _raw_main(args)
  File "/usr/local/lib/python2.7/dist-packages/beets/ui/__init__.py", line 1155, in _raw_main
    plugins.send('cli_exit', lib=lib)
  File "/usr/local/lib/python2.7/dist-packages/beets/plugins.py", line 458, in send
    result = handler(**arguments)
  File "/usr/local/lib/python2.7/dist-packages/beets/plugins.py", line 123, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/beetsplug/plexupdate.py", line 87, in update
    config['plex']['library_name'].get())
  File "/usr/local/lib/python2.7/dist-packages/beetsplug/plexupdate.py", line 41, in update_plex
    section_key = get_music_section(host, port, token, library_name)
  File "/usr/local/lib/python2.7/dist-packages/beetsplug/plexupdate.py", line 31, in get_music_section
    tree = ET.fromstring(r.raw)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1300, in XML
    parser.feed(text)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1640, in feed
    self._parser.Parse(data, 0)
TypeError: must be string or read-only buffer, not HTTPResponse
```

**Comment by amishb** [comment]
Can you post the relevant plex setting from your config file?

**Comment by sampsyo** [comment]
Hi! Thanks for reporting.

I'm a little confused about this -- I agree that we should make the change in the pull request (in fact, I'll merge it now), but I'm not sure how that problem could cause this error message or how the PR could fix it. In fact, I can't reproduce the problem:

    >>> from beetsplug import plexupdate
    >>> plexupdate.get_music_section('localhost', 32400, None, 'Music')
    '3'

What's so mystifying is that the error complains about getting an `HTTPResponse`. This should be impossible: we're passing it `r.text`, which is definitely a `unicode` object, never an `HTTPResponse`. Could something be wrong with your Requests installation? Maybe it's outdated?

**Comment by Nerten** [comment]
This happening because i have plex library names on cyrillic. Like
Фильмы (Movies)
Сериалы (TV Shows)

**Comment by sampsyo** [comment]
Ah yes, that would indeed cause an encoding error. What has me stumped, though, is that you didn't get an encoding error—it was the wrong type entirely. Mysterious!
