### ISSUE TITLE
sqlite3.OperationalError: unable to open database file when reimporting

### ISSUE THREAD

**Issue by defeo** [sampsyo/beets#1664]
When I try to reimport albums with `beet import -C <dir>` beets crashes with the following traceback: 

```
/data/Music/Albums/Los Beatles/1 (27 items)
Correcting tags from:
    Los Beatles - 1
To:
    The Beatles - 1
URL:
    http://musicbrainz.org/release/217fb7d2-40b7-4b4b-8860-8b72c970208a
(Similarity: 98.7%) (artist) (CD, 2011, US, Capitol Records)
Sending event: import_task_choice
Sending event: import_task_apply
Replacing item 2075: /data/Music/Albums/Los Beatles/1/14 Paperback Writer.mp3
Traceback (most recent call last):
  File "/home/defeo/.local/bin/beet", line 9, in <module>
    load_entry_point('beets==1.3.15', 'console_scripts', 'beet')()
  File "/home/defeo/.local/lib/python2.7/site-packages/beets/ui/__init__.py", line 1163, in main
    _raw_main(args)
  File "/home/defeo/.local/lib/python2.7/site-packages/beets/ui/__init__.py", line 1153, in _raw_main
    subcommand.func(lib, suboptions, subargs)
  File "/home/defeo/.local/lib/python2.7/site-packages/beets/ui/commands.py", line 875, in import_func
    import_files(lib, paths, query)
  File "/home/defeo/.local/lib/python2.7/site-packages/beets/ui/commands.py", line 852, in import_files
    session.run()
  File "/home/defeo/.local/lib/python2.7/site-packages/beets/importer.py", line 316, in run
    pl.run_parallel(QUEUE_SIZE)
  File "/home/defeo/.local/lib/python2.7/site-packages/beets/util/pipeline.py", line 301, in run
    out = self.coro.send(msg)
  File "/home/defeo/.local/lib/python2.7/site-packages/beets/util/pipeline.py", line 183, in coro
    func(*(args + (task,)))
  File "/home/defeo/.local/lib/python2.7/site-packages/beets/importer.py", line 1341, in apply_choices
    task.add(session.lib)
  File "/home/defeo/.local/lib/python2.7/site-packages/beets/importer.py", line 685, in add
    self.remove_replaced(lib)
  File "/home/defeo/.local/lib/python2.7/site-packages/beets/importer.py", line 759, in remove_replaced
    dup_item.remove()
  File "/home/defeo/.local/lib/python2.7/site-packages/beets/library.py", line 677, in remove
    super(Item, self).remove()
  File "/home/defeo/.local/lib/python2.7/site-packages/beets/library.py", line 296, in remove
    super(LibModel, self).remove()
  File "/home/defeo/.local/lib/python2.7/site-packages/beets/dbcore/db.py", line 405, in remove
    (self.id,)
  File "/home/defeo/.local/lib/python2.7/site-packages/beets/dbcore/db.py", line 665, in mutate
    cursor = self.db._connection().execute(statement, subvals)
sqlite3.OperationalError: unable to open database file
```

`beet ls` works normally, and it seems beets was able to retag just one file.

I am running version 1.3.15, installed via pip.

**Comment by sampsyo** [comment]
Wow, that's strange. I don't know why SQLite would suddenly stop working in the middle of an import. Could you please include your config and a verbose log, in the off chance there are clues there?

Any chance the beets database file is disappearing somehow? For example, I could imagine things could get nasty if the database file is inside the music directory and therefore gets moved or clobbered.

**Comment by defeo** [comment]
Config: 

```
defeo@beorn:~$ beet config
directory: /data/Music

import:
    move: yes
    languages: en
library: /data/beetslibrary.blb

paths:
    default: Albums/$albumartist/$album%aunique{albumartist album, albumdisambig albumtype original_year year label catalognum}/$track $title
    singleton: Misc/$artist/$title
    comp: Compilations/$album%aunique{albumartist album, albumdisambig albumtype original_year year label catalognum}/$track $title
```

Could't manage to retag even one file, this time:

```
defeo@beorn:~$ beet ls beatles paperback
Los Beatles - 1 - Paperback Writer
defeo@beorn:~$ beet -v modify -M beatles paperback artist="The Beatles"
user configuration: /home/defeo/.config/beets/config.yaml
data directory: /home/defeo/.config/beets
plugin paths: 
Sending event: pluginload
library database: /data/beetslibrary.blb
library directory: /data/Music
Sending event: library_opened
Modifying 1 items.
Los Beatles - 1 - Paperback Writer
  artist: Los Beatles -> The Beatles
Really modify and write tags (Y/n)? 
Sending event: write
Sending event: after_write
Traceback (most recent call last):
  File "/home/defeo/.local/bin/beet", line 9, in <module>
    load_entry_point('beets==1.3.15', 'console_scripts', 'beet')()
  File "/home/defeo/.local/lib/python2.7/site-packages/beets/ui/__init__.py", line 1163, in main
    _raw_main(args)
  File "/home/defeo/.local/lib/python2.7/site-packages/beets/ui/__init__.py", line 1153, in _raw_main
    subcommand.func(lib, suboptions, subargs)
  File "/home/defeo/.local/lib/python2.7/site-packages/beets/ui/commands.py", line 1314, in modify_func
    not opts.yes)
  File "/home/defeo/.local/lib/python2.7/site-packages/beets/ui/commands.py", line 1285, in modify_items
    obj.try_sync(write)
  File "/home/defeo/.local/lib/python2.7/site-packages/beets/library.py", line 624, in try_sync
    self.store()
  File "/home/defeo/.local/lib/python2.7/site-packages/beets/library.py", line 292, in store
    super(LibModel, self).store()
  File "/home/defeo/.local/lib/python2.7/site-packages/beets/dbcore/db.py", line 364, in store
    tx.mutate(query, subvars)
  File "/home/defeo/.local/lib/python2.7/site-packages/beets/dbcore/db.py", line 665, in mutate
    cursor = self.db._connection().execute(statement, subvals)
sqlite3.OperationalError: unable to open database file
```

The database file is in the correct location, I can open it and dump it with sqlite3. I really don't see how it could be disappearing. Maybe some concurrency problem?

I was having the same issue with 1.3.8 before upgrading to 1.3.15. I don't know if it could be related, but this is on (debian) ARM. beet was installed with `pip install --user`, Python version is 2.7.9.

**Comment by defeo** [comment]
Half interesting: my previous test succeeded in editing the id3 tag of the file. Yesterday I tried `beet modify -aM beatles artist="The Beatles"`, and no file was touched. But I guess this is not so surprising.

**Comment by defeo** [comment]
And then I tried `beet update -M beatles`, and got the same crash again. It looks like any attempt to write the database fails. I have write permissions, though.

**Comment by defeo** [comment]
Continuing my tests: just tried to import a new album, and got the same failure.

However I was able to import a new album just yesterday. Is there a way the database might have been corrupted? A way to regenerate it without re-importing everything?

**Comment by sampsyo** [comment]
Extremely strange. I suppose database corruption is possible. You can recreate the database by running `import -AWM` to disable autotagging, writing tags, and moving files—can you perhaps try that (but back up your current database!) to see if that clears anything up?

I am also tempted to blame something in the Debian+ARM toolchain. If you can, maybe compare on a similar setup but on a more mainstream desktop platform.

**Comment by defeo** [comment]
All right, this is silly. I just realized the database is in a directory where I have no write access. SQLite apparently requires write access for storing temporary files -sometimes-. Changed permissions and now everything works fine again.

Thanks for your help.

**Comment by sampsyo** [comment]
Thanks for investigating! I've opened a new issue about improving this failure mode.
