### ISSUE TITLE
Crash on UnicodeDecodeError: 'ascii' codec can't decode byte

### ISSUE THREAD

**Issue by teo** [sampsyo/beets#1666]
The import operation seems to crash, I'm guessing it might have something to do with characters in SoundCheck metadata. The files in question are MP3.

This happens in 1.3.15 as well as in current master.

```
beet -vv import -A public/Disks/red2/Music
(...)
Traceback (most recent call last):
  File "/usr/bin/beet", line 9, in <module>
    load_entry_point('beets==1.3.16', 'console_scripts', 'beet')()
  File "/usr/lib/python2.7/site-packages/beets/ui/__init__.py", line 1163, in main
    _raw_main(args)
  File "/usr/lib/python2.7/site-packages/beets/ui/__init__.py", line 1153, in _raw_main
    subcommand.func(lib, suboptions, subargs)
  File "/usr/lib/python2.7/site-packages/beets/ui/commands.py", line 860, in import_func
    import_files(lib, paths, query)
  File "/usr/lib/python2.7/site-packages/beets/ui/commands.py", line 837, in import_files
    session.run()
  File "/usr/lib/python2.7/site-packages/beets/importer.py", line 318, in run
    pl.run_parallel(QUEUE_SIZE)
  File "/usr/lib/python2.7/site-packages/beets/util/pipeline.py", line 251, in run
    msg = self.coro.next()
  File "/usr/lib/python2.7/site-packages/beets/importer.py", line 1191, in read_tasks
    for t in task_factory.tasks():
  File "/usr/lib/python2.7/site-packages/beets/importer.py", line 1036, in tasks
    tasks = self._create(self.album(paths, dirs))
  File "/usr/lib/python2.7/site-packages/beets/importer.py", line 1115, in album
    items = map(self.read_item, paths)
  File "/usr/lib/python2.7/site-packages/beets/importer.py", line 1165, in read_item
    return library.Item.from_path(path)
  File "/usr/lib/python2.7/site-packages/beets/library.py", line 482, in from_path
    i.read(path)
  File "/usr/lib/python2.7/site-packages/beets/library.py", line 539, in read
    value = getattr(mediafile, key)
  File "/usr/lib/python2.7/site-packages/beets/mediafile.py", line 1079, in __get__
    out = style.get(mediafile.mgfile)
  File "/usr/lib/python2.7/site-packages/beets/mediafile.py", line 553, in get
    return _sc_decode(data)[self.index]
  File "/usr/lib/python2.7/site-packages/beets/mediafile.py", line 218, in _sc_decode
    soundcheck = soundcheck.replace(' ', '').decode('hex')
UnicodeDecodeError: 'ascii' codec can't decode byte 0xef in position 93: ordinal not in range(128)
```

**Comment by sampsyo** [comment]
Yep, this is a bug. Thanks for reporting! (Another unforeseen consequence of `unicode_literals`.)

So I can construct a test case, can you please provide a sample audio file that triggers the bug?

**Comment by teo** [comment]
I have the directory with the album that triggered the issue but I don't think it's legal to share here.

**Comment by sampsyo** [comment]
Yes, posting publicly wouldn't be a good idea. But perhaps you can email me privately? (My address is on the profile page.) To make the file useless for the music itself but still useful for the tags, you can truncate it to a few kilobytes.

**Comment by sampsyo** [comment]
Thank you for the sample data! Just committed a fix.
