### ISSUE TITLE
(thumbnails plugin) segmentation fault

### ISSUE THREAD

**Issue by simonbcn** [sampsyo/beets#1674]
Ubuntu 14.04 64 bits
beets git version
```
beets version 1.3.16
plugins: badfiles, convert, discogs, duplicates, fetchart, info, lastgenre, replaygain, scrub, thumbnails
```
```
$ beet config
paths:
    default: $albumartist/$album/$track - $title
    singleton: $artist - $title
    comp: Varios/$album/$track - $title
convert:
    auto: yes
    tmpdir: /tmp
    command: ffmpeg -i $source -y -codec:a libmp3lame -vn -qscale:a 1 $dest
    extension: mp3
    embed: yes
    quiet: yes
    threads: 7
    never_convert_lossy_files: yes
    format: mp3
    dest:
    copy_album_art: no
    max_bitrate: 500

    paths: {}
    pretend: no
    formats:
        alac:
            command: ffmpeg -i $source -y -vn -acodec alac $dest
            extension: m4a
        aac:
            command: ffmpeg -i $source -y -vn -acodec libfaac -aq 100 $dest
            extension: m4a
        opus: ffmpeg -i $source -y -vn -acodec libopus -ab 96k $dest
        mp3: ffmpeg -i $source -y -vn -aq 2 $dest
        flac: ffmpeg -i $source -y -vn -acodec flac $dest
        ogg: ffmpeg -i $source -y -vn -acodec libvorbis -aq 2 $dest
        wma: ffmpeg -i $source -y -vn -acodec wmav2 -vn $dest
scrub:
    auto: yes
thumbnails:
    force: yes
    auto: yes
    dolphin: no
fetchart:
    auto: yes
    maxwidth: 300
    cautious: yes
    minwidth: 0
    sources:
    - coverart
    - itunes
    - amazon
    - albumart
    cover_names:
    - cover
    - front
    - art
    - album
    - folder
    remote_priority: no
    enforce_ratio: no
duplicates:
    path: yes
    count: no
    full: no
    format: ''
    keys: []
    move: ''
    tag: ''
    copy: ''
    tiebreak: {}
    album: no
    strict: no
    checksum: ''
    merge: no
    delete: no
zero:
    fields: comments
    update_database: yes
embedart:
    auto: yes
    maxwidth: 300
    remove_art_file: yes
replaygain:
    backend: bs1770gain
    overwrite: yes
    targetlevel: 89
    auto: yes
    chunk_at: 5000
    method: replaygain
lastgenre:
    canonical: yes
    count: 1
    source: album
    force: yes
    min_weight: 10
    auto: yes
    whitelist: yes
    separator: ', '
    fallback:
library: /home/simon/.beets/musiclibrary.blb

plugins: convert replaygain lastgenre fetchart info discogs scrub duplicates badfiles replaygain thumbnails
directory: "/home/simon/M\xFAsica/"

import:
    art: yes
    languages: es en

match:
    strong_rec_thresh: 0.3
    max_rec:
        missing_tracks: strong
discogs:
    tokenfile: discogs_token.json
    apikey: REDACTED
    apisecret: REDACTED
    source_weight: 0.5
```
```
$ beet -v import /dunehd/Musica\ pendiente/Avicii-Stories-CD-FLAC-2015-VOLDiES/
user configuration: /home/simon/.config/beets/config.yaml
data directory: /home/simon/.config/beets
plugin paths: 
Sending event: pluginload
artresizer: method is (2, (6, 7, 7))
thumbnails: using IM to write metadata
thumbnails: using GIO to compute URIs
library database: /home/simon/.beets/musiclibrary.blb
library directory: /home/simon/Música
Sending event: library_opened
Sending event: import_begin
Sending event: import_task_created
Sending event: import_task_start
Looking up: /dunehd/Musica pendiente/Avicii-Stories-CD-FLAC-2015-VOLDiES
Tagging Avicii - Stories
No album IDs found.
Search terms: Avicii - Stories
Album might be VA: False
discogs: Communication error while searching for 'Avicii Stories': Only unicode objects are escapable. Got XQoOecWCCgbpXpkCOLJgobbSXIpjJAQkKMsDjzHb of type <type 'str'>.
Evaluating 5 candidates.
Candidate: Avicii - Stories
Success. Distance: 0.00
Candidate: Avicii - Stories
Success. Distance: 0.00
Candidate: Avicii - Stories
Success. Distance: 0.00
Candidate: Avicii - Stories
Success. Distance: 0.03
Candidate: Avicii - Stories
Success. Distance: 0.05
Sending event: import_task_choice
found duplicates: [550]
This album is already in the library!
Sending event: import_task_apply
0 of 14 items replaced
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: write
Sending event: after_write
Sending event: database_change
Sending event: write
Sending event: after_write
Sending event: database_change
Sending event: write
Sending event: after_write
Sending event: database_change
Sending event: write
Sending event: after_write
Sending event: database_change
Sending event: write
Sending event: after_write
Sending event: database_change
Sending event: write
Sending event: after_write
Sending event: database_change
Sending event: write
Sending event: after_write
Sending event: database_change
Sending event: write
Sending event: after_write
Sending event: database_change
Sending event: write
Sending event: after_write
Sending event: database_change
Sending event: write
Sending event: after_write
Sending event: database_change
Sending event: write
Sending event: after_write
Sending event: database_change
Sending event: write
Sending event: after_write
Sending event: database_change
Sending event: write
Sending event: after_write
Sending event: database_change
Sending event: write
Sending event: after_write
Sending event: database_change
replaygain: analyzing Avicii - Stories
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
artresizer: ImageMagick resizing /tmp/tmp92ZG75.jpg to /tmp/tmpFDq4xY.jpg
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
removing 14 old duplicated items
Sending event: database_change
Sending event: item_removed
deleting duplicate /home/simon/Música/Avicii/Stories/01 - Waiting for Love.mp3
Sending event: database_change
Sending event: item_removed
deleting duplicate /home/simon/Música/Avicii/Stories/02 - Talk to Myself.mp3
Sending event: database_change
Sending event: item_removed
deleting duplicate /home/simon/Música/Avicii/Stories/03 - Touch Me.mp3
Sending event: database_change
Sending event: item_removed
deleting duplicate /home/simon/Música/Avicii/Stories/04 - Ten More Days.mp3
Sending event: database_change
Sending event: item_removed
deleting duplicate /home/simon/Música/Avicii/Stories/05 - For a Better Day.mp3
Sending event: database_change
Sending event: item_removed
deleting duplicate /home/simon/Música/Avicii/Stories/06 - Broken Arrows.mp3
Sending event: database_change
Sending event: item_removed
deleting duplicate /home/simon/Música/Avicii/Stories/07 - True Believer.mp3
Sending event: database_change
Sending event: item_removed
deleting duplicate /home/simon/Música/Avicii/Stories/08 - City Lights.mp3
Sending event: database_change
Sending event: item_removed
deleting duplicate /home/simon/Música/Avicii/Stories/09 - Pure Grinding.mp3
Sending event: database_change
Sending event: item_removed
deleting duplicate /home/simon/Música/Avicii/Stories/10 - Sunset Jesus.mp3
Sending event: database_change
Sending event: item_removed
deleting duplicate /home/simon/Música/Avicii/Stories/11 - Can’t Catch Me.mp3
Sending event: database_change
Sending event: item_removed
deleting duplicate /home/simon/Música/Avicii/Stories/12 - Somewhere in Stockholm.mp3
Sending event: database_change
Sending event: item_removed
deleting duplicate /home/simon/Música/Avicii/Stories/13 - Trouble.mp3
Sending event: database_change
Sending event: database_change
Sending event: item_removed
deleting duplicate /home/simon/Música/Avicii/Stories/14 - Gonna Love Ya.mp3
Sending event: item_copied
Sending event: database_change
Sending event: database_change
Sending event: write
Sending event: after_write
Sending event: item_copied
Sending event: database_change
Sending event: database_change
Sending event: write
Sending event: after_write
Sending event: item_copied
Sending event: database_change
Sending event: database_change
Sending event: write
Sending event: after_write
Sending event: item_copied
Sending event: database_change
Sending event: database_change
Sending event: write
Sending event: after_write
Sending event: item_copied
Sending event: database_change
Sending event: database_change
Sending event: write
Sending event: after_write
Sending event: item_copied
Sending event: database_change
Sending event: database_change
Sending event: write
Sending event: after_write
Sending event: item_copied
Sending event: database_change
Sending event: database_change
Sending event: write
Sending event: after_write
Sending event: item_copied
Sending event: database_change
Sending event: database_change
Sending event: write
Sending event: after_write
Sending event: item_copied
Sending event: database_change
Sending event: database_change
Sending event: write
Sending event: after_write
Sending event: item_copied
Sending event: database_change
Sending event: database_change
Sending event: write
Sending event: after_write
Sending event: item_copied
Sending event: database_change
Sending event: database_change
Sending event: write
Sending event: after_write
Sending event: item_copied
Sending event: database_change
Sending event: database_change
Sending event: write
Sending event: after_write
Sending event: item_copied
Sending event: database_change
Sending event: database_change
Sending event: write
Sending event: after_write
Sending event: item_copied
Sending event: database_change
Sending event: database_change
Sending event: write
Sending event: after_write
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: import_task_files
Sending event: art_set
[1]    18227 segmentation fault  beet -v import /dunehd/Musica\ pendiente/Avicii-Stories-CD-FLAC-2015-VOLDiES/
```

**Comment by sampsyo** [comment]
Please see #1433.

**Comment by simonbcn** [comment]
It still fails, now with another error ([complete output](http://pastebin.com/eKKt7WxM)):
```
$ beet -vv import /dunehd/Musica\ pendiente/Eros\ Ramazzotti\ -\ Eros\ 30\ \(2014\)\ FLAC/
....
thumbnails: generating thumbnail for Eros Ramazzotti - Eros 30
artresizer: ImageMagick resizing /home/simon/Música/Eros Ramazzotti/Eros 30/cover.1.jpg to /home/simon/.cache/thumbnails/large/0828df789bd167971fa265da40f18e06.png
Traceback (most recent call last):
  File "/usr/local/bin/beet", line 9, in <module>
    load_entry_point('beets==1.3.16', 'console_scripts', 'beet')()
  File "/usr/local/lib/python2.7/dist-packages/beets-1.3.16-py2.7.egg/beets/ui/__init__.py", line 1163, in main
    _raw_main(args)
  File "/usr/local/lib/python2.7/dist-packages/beets-1.3.16-py2.7.egg/beets/ui/__init__.py", line 1153, in _raw_main
    subcommand.func(lib, suboptions, subargs)
  File "/usr/local/lib/python2.7/dist-packages/beets-1.3.16-py2.7.egg/beets/ui/commands.py", line 860, in import_func
    import_files(lib, paths, query)
  File "/usr/local/lib/python2.7/dist-packages/beets-1.3.16-py2.7.egg/beets/ui/commands.py", line 837, in import_files
    session.run()
  File "/usr/local/lib/python2.7/dist-packages/beets-1.3.16-py2.7.egg/beets/importer.py", line 320, in run
    pl.run_sequential()
  File "/usr/local/lib/python2.7/dist-packages/beets-1.3.16-py2.7.egg/beets/util/pipeline.py", line 378, in run_sequential
    list(self.pull())
  File "/usr/local/lib/python2.7/dist-packages/beets-1.3.16-py2.7.egg/beets/util/pipeline.py", line 455, in pull
    out = coro.send(msg)
  File "/usr/local/lib/python2.7/dist-packages/beets-1.3.16-py2.7.egg/beets/util/pipeline.py", line 160, in coro
    task = func(*(args + (task,)))
  File "/usr/local/lib/python2.7/dist-packages/beets-1.3.16-py2.7.egg/beets/importer.py", line 1380, in manipulate_files
    session=session,
  File "/usr/local/lib/python2.7/dist-packages/beets-1.3.16-py2.7.egg/beets/importer.py", line 679, in manipulate_files
    plugins.send('import_task_files', session=session, task=self)
  File "/usr/local/lib/python2.7/dist-packages/beets-1.3.16-py2.7.egg/beets/plugins.py", line 458, in send
    result = handler(**arguments)
  File "/usr/local/lib/python2.7/dist-packages/beets-1.3.16-py2.7.egg/beets/plugins.py", line 123, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/beets-1.3.16-py2.7.egg/beetsplug/fetchart.py", line 457, in assign_art
    album.set_art(path, not src_removed)
  File "/usr/local/lib/python2.7/dist-packages/beets-1.3.16-py2.7.egg/beets/library.py", line 1068, in set_art
    plugins.send('art_set', album=self)
  File "/usr/local/lib/python2.7/dist-packages/beets-1.3.16-py2.7.egg/beets/plugins.py", line 458, in send
    result = handler(**arguments)
  File "/usr/local/lib/python2.7/dist-packages/beets-1.3.16-py2.7.egg/beets/plugins.py", line 123, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/beets-1.3.16-py2.7.egg/beetsplug/thumbnails.py", line 131, in process_album
    wrote &= self.make_cover_thumbnail(album, 256, LARGE_DIR)
  File "/usr/local/lib/python2.7/dist-packages/beets-1.3.16-py2.7.egg/beetsplug/thumbnails.py", line 155, in make_cover_thumbnail
    util.syspath(target))
  File "/usr/local/lib/python2.7/dist-packages/beets-1.3.16-py2.7.egg/beets/util/artresizer.py", line 176, in resize
    return func(maxwidth, path_in, path_out)
  File "/usr/local/lib/python2.7/dist-packages/beets-1.3.16-py2.7.egg/beets/util/artresizer.py", line 95, in im_resize
    b'-resize', b'{0}x^>'.format(maxwidth), path_out
  File "/usr/local/lib/python2.7/dist-packages/beets-1.3.16-py2.7.egg/beets/util/__init__.py", line 703, in command_output
    cmd=b' '.join(cmd),
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 13: ordinal not in range(128)
```

**Comment by sampsyo** [comment]
This looks like a separate bug. Can you please file it separately?
