### ISSUE TITLE
Cannot install on Python 3.5.0 (x64) Windows

### ISSUE THREAD

**Issue by FatKiwi** [sampsyo/beets#1712]
pip install beets

Collecting beets
  Using cached beets-1.3.15.tar.gz
Collecting enum34>=1.0.4 (from beets)
  Using cached enum34-1.0.4.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "C:\Users\***\AppData\Local\Temp\pip-build-x6hf4_9c\enum34\enum\__init__.py", line 371, in __getattr__
        return cls._member_map_[name]
    KeyError: '_convert'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "<string>", line 3, in <module>
      File "c:\users\***\appdata\local\programs\python\python35\lib\site-packages\setuptools\__init__.py", line 11, in <module>
        from setuptools.extension import Extension
      File "c:\users\***\appdata\local\programs\python\python35\lib\site-packages\setuptools\extension.py", line 8, in <module>
        from .dist import _get_unpatched
      File "c:\users\***\appdata\local\programs\python\python35\lib\site-packages\setuptools\dist.py", line 16, in <module>
        from setuptools.depends import Require
      File "c:\users\***\appdata\local\programs\python\python35\lib\site-packages\setuptools\depends.py", line 6, in <module>
        from setuptools import compat
      File "c:\users\***\appdata\local\programs\python\python35\lib\site-packages\setuptools\compat.py", line 45, in <module>
        import http.client as httplib
      File "c:\users\***\appdata\local\programs\python\python35\lib\http\client.py", line 71, in <module>
        import email.parser
      File "c:\users\***\appdata\local\programs\python\python35\lib\email\parser.py", line 12, in <module>
        from email.feedparser import FeedParser, BytesFeedParser
      File "c:\users\***\appdata\local\programs\python\python35\lib\email\feedparser.py", line 27, in <module>
        from email import message
      File "c:\users\***\appdata\local\programs\python\python35\lib\email\message.py", line 16, in <module>
        from email import utils
      File "c:\users\***\appdata\local\programs\python\python35\lib\email\utils.py", line 29, in <module>
        import socket
      File "c:\users\***\appdata\local\programs\python\python35\lib\socket.py", line 73, in <module>
        IntEnum._convert(
      File "C:\Users\***\AppData\Local\Temp\pip-build-x6hf4_9c\enum34\enum\__init__.py", line 373, in __getattr__
        raise AttributeError(name)
    AttributeError: _convert

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\***\AppData\Local\Temp\pip-build-x6hf4_9c\enum34

**Comment by sampsyo** [comment]
Python 3 isn't supported.

**Comment by FatKiwi** [comment]
Oops! Sorry, should have checked earlier. Any chance to support it in the future?

**Comment by sampsyo** [comment]
I sure hope so! Here's a blog post I wrote about py3k support a long time ago: http://beets.radbox.org/blog/py3k.html

It's somewhat outdated, and we're now a lot closer to having all our dependencies ready. Another audit could be in order.

**Comment by FatKiwi** [comment]
Thanks, sounds great!
