### ISSUE TITLE
Beets 1.3.15 on Unraid

### ISSUE THREAD

**Issue by mannp** [sampsyo/beets#1732]
Hi there

I am struggling to find the solution on google to the following error and would appreciate a little help please to track the issue down :)

local@Tower-32:/$ beet
Traceback (most recent call last):
  File "/usr/bin/beet", line 9, in <module>
    load_entry_point('beets==', 'console_scripts', 'beet')()
  File "/usr/lib/python2.7/site-packages/setuptools-0.9.8-py2.7.egg/pkg_resources.py", line 378, in load_entry_point
  File "/usr/lib/python2.7/site-packages/setuptools-0.9.8-py2.7.egg/pkg_resources.py", line 2566, in load_entry_point
  File "/usr/lib/python2.7/site-packages/setuptools-0.9.8-py2.7.egg/pkg_resources.py", line 2260, in load
  File "/usr/lib/python2.7/site-packages/beets/__init__.py", line 19, in <module>
    import beets.library
  File "/usr/lib/python2.7/site-packages/beets/library.py", line 29, in <module>
    from beets.mediafile import MediaFile, MutagenError, UnreadableFileError
  File "/usr/lib/python2.7/site-packages/beets/mediafile.py", line 58, in <module>
    from beets.util import displayable_path, syspath
  File "/usr/lib/python2.7/site-packages/beets/util/__init__.py", line 19, in <module>
    import ctypes
  File "/usr/lib/python2.7/ctypes/__init__.py", line 10, in <module>
    from _ctypes import Union, Structure, Array
ImportError: libffi.so.6: cannot open shared object file: No such file or directory
local@Tower-32:/$

**Comment by xsteadfastx** [comment]
i have no experience with unraid but it looks like libffi6 is not installed. on ubuntu you could find out if its installed with `dpkg -l|grep libffi`.

**Comment by mannp** [comment]
Thanks for a response. I did think of that but couldn't find out why, as v1.3.14 worked fine and no libs have been removed since. Does 1.3.15 need a new version of libffi perhaps.

**Comment by sampsyo** [comment]
We did start importing ctypes by default in our utilities module, which looks like it requires cffi. This is only really necessary for Windows (unless I'm misremembering), though, so maybe we should walk that back.

In the mean time, though, it looks like Unraid has given you an incomplete Python installation. This should work:

    $ python -c 'import ctypes'

but it looks like it won't on your system. This is probably worth reporting as a bug to the Unraid people.

**Comment by mannp** [comment]
You are right, unfortunately it doesn't work.

local@Tower-32:/usr/lib/python2.7$ python -c 'import ctypes'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "ctypes/__init__.py", line 10, in <module>
    from _ctypes import Union, Structure, Array
ImportError: libffi.so.6: cannot open shared object file: No such file or directory
local@Tower-32:/usr/lib/python2.7$ 

I will report, but its on a v5 system so support is limited as most have moved to v6, but will give it a go.

Thanks for your inputs.

**Comment by sampsyo** [comment]
OK, sorry for the messy situation in any case. I just pushed a fix that should suppress this for now by importing ctypes only on Windows, where it is needed. But there's always a chance we use ctypes somewhere else in the codebase (or in a plugin), so it's worth keeping an eye out anyway.

**Comment by mannp** [comment]
Thats excellent and prompt service indeed, thanks for the quick turnaround on a fix.

Here's hoping 1.3.16 release is coming soon :)  as I am not running the latest source, but still appreciated.
