### ISSUE TITLE
UnicodeDecodeError with the convert plugin

### ISSUE THREAD

**Issue by snk4ever** [sampsyo/beets#1735]
I'm trying to convert the flac part of my library to mp3 with beets + the convert plugin.

Here is my plugin configuration:
> convert:
> auto: yes
> copy_album_art: yes
> embed: no
> never_convert_lossy_files: yes
> format: mp3
> formats:
> mp3:
> command: ffmpeg -i $source -y -vn -aq 0 $dest
> extension: mp3

And my command to launch the conversion:
beet convert format:flac -d /data/musicFlacBackup/ -k --pretend

I am running Debian 7 x64.

The resulting log:

```
beet convert format:flac -d /data/musicFlacBackup/ -k --pretend
convert: mv /data/music/Albums/Daniel Balavoine/1990-L'Essentiel/01 L'Aziza.flac /data/musicFlacBackup/Albums/Daniel Balavoine/1990-L'Essentiel/01 L'Aziza.flac
convert: ffmpeg -i /data/musicFlacBackup/Albums/Daniel Balavoine/1990-L'Essentiel/01 L'Aziza.flac -y -vn -aq 0 /data/music/Albums/Daniel Balavoine/1990-L'Essentiel/01 L'Aziza.mp3
convert: mv /data/music/Albums/Daniel Balavoine/1990-L'Essentiel/02 Aimer est plus fort que d'être aimé.flac /data/musicFlacBackup/Albums/Daniel Balavoine/1990-L'Essentiel/02 Aimer est plus fort que d'être aimé.flac
convert: mv /data/music/Albums/Daniel Balavoine/1990-L'Essentiel/03 Sauver l'amour.flac /data/musicFlacBackup/Albums/Daniel Balavoine/1990-L'Essentiel/03 Sauver l'amour.flac
convert: ffmpeg -i /data/musicFlacBackup/Albums/Daniel Balavoine/1990-L'Essentiel/03 Sauver l'amour.flac -y -vn -aq 0 /data/music/Albums/Daniel Balavoine/1990-L'Essentiel/03 Sauver l'amour.mp3
Traceback (most recent call last):
File "/usr/local/bin/beet", line 9, in <module>
load_entry_point('beets==1.3.15', 'console_scripts', 'beet')()
File "/usr/local/lib/python2.7/dist-packages/beets/ui/__init__.py", line 1163, in main
_raw_main(args)
File "/usr/local/lib/python2.7/dist-packages/beets/ui/__init__.py", line 1153, in _raw_main
subcommand.func(lib, suboptions, subargs)
File "/usr/local/lib/python2.7/dist-packages/beetsplug/convert.py", line 388, in convert_func
pipe.run_parallel()
File "/usr/local/lib/python2.7/dist-packages/beets/util/pipeline.py", line 347, in run
self.coro.send(msg)
File "/usr/local/lib/python2.7/dist-packages/beetsplug/convert.py", line 264, in convert_item
self.encode(command, original, converted, pretend)
File "/usr/local/lib/python2.7/dist-packages/beetsplug/convert.py", line 191, in encode
self._log.info(' '.join(args))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 92: ordinal not in range(128)
```

**Comment by sampsyo** [comment]
Thanks for the report! I've just pushed a fix.
