### ISSUE TITLE
Trouble importing on Mac OSX

### ISSUE THREAD

**Issue by ovizii** [sampsyo/beets#1752]
I've been using Macports to get this running as far as I can but I'm stuck with these errors right now:

```
shiny:~ ovi$ beet import /Users/ovi/Music/iTunes/iTunes\ Media/\!DelaDap
Traceback (most recent call last):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/bin/beet", line 9, in <module>
    load_entry_point('beets==1.3.15', 'console_scripts', 'beet')()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/beets/ui/__init__.py", line 1163, in main
    _raw_main(args)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/beets/ui/__init__.py", line 1149, in _raw_main
    subcommands, plugins, lib = _setup(options, lib)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/beets/ui/__init__.py", line 1028, in _setup
    plugins = _load_plugins(config)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/beets/ui/__init__.py", line 1014, in _load_plugins
    plugins.send("pluginload")
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/beets/plugins.py", line 457, in send
    for handler in event_handlers()[event]:
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/beets/plugins.py", line 440, in event_handlers
    for plugin in find_plugins():
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/beets/plugins.py", line 288, in find_plugins
    _instances[cls] = cls()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/beetsplug/replaygain.py", line 813, in __init__
    self.config, self._log
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/beetsplug/replaygain.py", line 378, in __init__
    self._import_gst()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/beetsplug/replaygain.py", line 445, in _import_gst
    gi.require_version('Gst', '1.0')
AttributeError: 'module' object has no attribute 'require_version'
```

Any hints are much appreciated.

**Comment by ovizii** [comment]
sudo su
then it works. is this really needed?
```
h-3.2# beet import /Users/ovi/Music/iTunes/iTunes\ Media/\!DelaDap

/Users/ovi/Music/iTunes/iTunes Media/!DelaDap/Cigani Ruzsa + Angelo (12 items)
Tagging:
    !DelaDap - Cigani Ruzsa + Angelo
URL:
    http://musicbrainz.org/release/9de98b44-f503-4e83-90dc-4b975f621f7c
(Similarity: 100.0%) (CD, 2004, AT, ecco.chamber)

/Users/ovi/Music/iTunes/iTunes Media/!DelaDap/Dela Paji (14 items)
Tagging:
    !DelaDap - Dela Paji
URL:
    http://musicbrainz.org/release/1091cb58-4a8e-4274-b455-fe9a2688e2aa
(Similarity: 98.0%) (missing tracks) (CD, 2006, AT, Chat Chapeau)
Missing tracks (1/15 - 6.7%):
 ! Spielurh (#15) (1:00)
[A]pply, More candidates, Skip, Use as-is, as Tracks, Group albums,
Enter search, enter Id, aBort?
```

**Comment by sampsyo** [comment]
The exception is coming from the `replaygain` plugin, which is for some reason not getting what it needs from its GStreamer-related dependencies. I'm not really sure why—but I would recommend either disabling the plugin or choosing a different backend.

Sudo should not be required.

Maybe there's a different Python module installed called `gi` that's getting confused here?

**Comment by ovizii** [comment]
aacgain seems to work from Macports. no more errors even without sudo :-)

Thanks!
