### ISSUE TITLE
Cleanly recover when mp3gain crashes:

### ISSUE THREAD

**Issue by wting** [sampsyo/beets#568]
```shell
/home/ting/media/inbox/music/Nujabes/Nujabes/Ristorante Mixtape/Side B (15 items)
Finding tags for album "Nujabes - Ristorante Mixtape".
Candidates:
1. Nujabes - Good Music Cuisine: Ristorante Nujabes (39.1%) (missing tracks, tracks, album) (2xDigital Media, 2004, XW, Hyde Out Recordings)
2. Nujabes - Metaphorical Music (30.9%) (tracks, album) (CD, 2003, JP, Dimid Recordings)
3. Nujabes - Next View (29.4%) (unmatched tracks, tracks, album) (7" Vinyl, 2003, JP, Hyde Out Recordings)
4. Nujabes - Luv(sic) Part 5 (24.5%) (unmatched tracks, tracks, album) (Digital Media, 2012, JP, Hyde Out Recordings)
5. Nujabes - Good Music Cuisine: Ristorante Nujabes (22.8%) (tracks, missing tracks, album) (Cassette, 2002, JP, Hyde Out Recordings)
# selection (default 1), Skip, Use as-is, as Tracks, Group albums,
Enter search, enter Id, aBort? U
This album is already in the library!
[S]kip new, Keep both, Remove old? R
replaygain: analysis failed (mp3gain exited with status 1)
Traceback (most recent call last):
  File "/home/ting/.virtualenvs/beets/bin/beet", line 9, in <module>
    load_entry_point('beets==1.3.3', 'console_scripts', 'beet')()
  File "/home/ting/.virtualenvs/beets/local/lib/python2.7/site-packages/beets/ui/__init__.py", line 946, in main
    _raw_main(args)
  File "/home/ting/.virtualenvs/beets/local/lib/python2.7/site-packages/beets/ui/__init__.py", line 937, in _raw_main
    subcommand.func(lib, suboptions, subargs)
  File "/home/ting/.virtualenvs/beets/local/lib/python2.7/site-packages/beets/ui/commands.py", line 843, in import_func
    import_files(lib, paths, query)
  File "/home/ting/.virtualenvs/beets/local/lib/python2.7/site-packages/beets/ui/commands.py", line 779, in import_files
    session.run()
  File "/home/ting/.virtualenvs/beets/local/lib/python2.7/site-packages/beets/importer.py", line 347, in run
    pl.run_parallel(QUEUE_SIZE)
  File "/home/ting/.virtualenvs/beets/local/lib/python2.7/site-packages/beets/util/pipeline.py", line 243, in run
    out = self.coro.send(msg)
  File "/home/ting/.virtualenvs/beets/local/lib/python2.7/site-packages/beets/importer.py", line 838, in plugin_stage
    item.load()
  File "/home/ting/.virtualenvs/beets/local/lib/python2.7/site-packages/beets/dbcore/db.py", line 304, in load
    self.update(dict(stored_obj))
TypeError: 'NoneType' object is not iterable
╭─ting@noa ~  ‹python-2.7.3› ‹beets›  
╰─➤                                          
```

**Comment by sampsyo** [comment]
This seems less obvious than I apparently thought last year (the exception doesn't seem to be related to mp3gain crashing?). Closing unless there's more information.
